### ISSUE TITLE
Javadoc search results link to incorrect URLs

### ISSUE THREAD

**Issue by alex-chew** [awslabs/smithy#1006]
From the [Javadoc](https://awslabs.github.io/smithy/javadoc/1.15.0/), if I type a symbol name (e.g. ModelAssembler) in the search input and then click on any result, I'm directed to [a 404 page](https://awslabs.github.io/smithy/javadoc/1.15.0/undefined/software/amazon/smithy/model/loader/ModelAssembler.html). On the other hand, navigating to [the desired symbol](https://awslabs.github.io/smithy/javadoc/1.15.0/software/amazon/smithy/model/loader/ModelAssembler.html) via the package list works as expected.

I've also noticed that, when my browser loads the Javadoc home page, it gets 404s for the following resources:

* https://awslabs.github.io/smithy/javadoc/1.15.0/module-search-index.zip
* https://awslabs.github.io/smithy/javadoc/1.15.0/tag-search-index.zip
* https://awslabs.github.io/smithy/javadoc/1.15.0/module-search-index.js
* https://awslabs.github.io/smithy/javadoc/1.15.0/tag-search-index.js

**Comment by adamthom-amzn** [comment]
Looks like https://bugs.openjdk.java.net/browse/JDK-8215291

**Comment by adamthom-amzn** [comment]
the links from search will be fixed with the next smithy release, in its javadocs.
