### ISSUE TITLE
Protocol test InputAndOutputWithTimestampHeaders contains quotes for RestJSON but not for RestXml

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy#1015]
### Links to the code

RestJSON https://github.com/awslabs/smithy/blob/78a3ac958ea442695cf66ad0f5808768e1f553bf/smithy-aws-protocol-tests/model/restJson1/http-headers.smithy#L108-L121

RestXML: https://github.com/awslabs/smithy/blob/75928a7c69b2a156382b5d8bc87a6991f5fea64e/smithy-aws-protocol-tests/model/restXml/http-headers.smithy#L93-L106

### Observation

This appears to be a bug, as the behavior for the list of timestamps should be same across protocols

### Additional Context
* This issue was noticed while bumping AWS SDK for JavaScript (v3) to smithy 1.15.x https://github.com/aws/aws-sdk-js-v3/pull/3091#issuecomment-991179106
* The protocol tests for quotes string were added in https://github.com/awslabs/smithy/pull/986

**Comment by gosar** [comment]
In https://github.com/awslabs/smithy/pull/1023 reverted escaping of timestamp header in restJson1. Now restJson1 and restXml are same.
