### ISSUE TITLE
Shape ID naming suggestion for the documentation

### ISSUE THREAD

**Issue by kennethchoe** [awslabs/smithy#1032]
Sample code snippet in the documentation serves as a bible for new comers. Even though I find certain things didn't make sense to me at first, I assumed there must have been a good reason for naming as such and followed as-is.

After going through a project that has decent size of smithy model, I speculate if the code snippets' naming convention serves as a source of best practice, especially for shape ID naming convention.

Because shape IDs must be globally unique, it makes sense to put the type of shape as a postfix (or prefix if it is a verb).

https://awslabs.github.io/smithy/1.0/spec/core/model.html#put-lifecycle
```
operation PutForecast {
    input: PutForecastInput,
    output: PutForecastOutput
}
```
`input: PutForecastInput` is great. It has Input as a postfix.

https://awslabs.github.io/smithy/1.0/spec/core/idl.html#operation-shape
```
operation PingService {
    input: Input,
    output: Output,
    errors: [Unavailable, BadRequest]
}
```
What about naming errors as `[UnavailableError, BadRequestError]`?

https://awslabs.github.io/smithy/1.0/spec/core/model.html#resource-lifecycle-operations
```
resource Forecast {
    identifiers: {
        forecastId: ForecastId,
    },
    put: PutForecast,
    create: CreateForecast,
    read: GetForecast,
    update: UpdateForecast,
    delete: DeleteForecast,
    list: ListForecasts,
}
```
All lifecycle operation shapes are named after the operation (`put: PutForcast`), except for read operation (`read: GetForcast`). It should be consistent, unless there is a good reason. If you want Get for `read`, why not Get for `list` also?

https://awslabs.github.io/smithy/1.0/spec/core/idl.html#idl-resource
```
resource Model {
    identifiers: {
        modelId: String,
    },
    read: GetModel,
}
```
Model could be renamed as ModelResource, because chances are, you will have Model structure somewhere in the file. (This actually happened in my project.)

**Comment by mtdowling** [comment]
Thanks for the feedback. Regarding "Get" for read lifecycles: we wanted to stick to CRUDL for resource operations so they're familiar, but virtually every read style operation in AWS and Amazon uses Get as the corresponding verb.
