### ISSUE TITLE
Smithy artifacts not in maven central

### ISSUE THREAD

**Issue by jpmartin2** [awslabs/smithy#104]
As far as I can tell, it looks like none of the software.amazon.smithy artifacts have been uploaded to maven central. It also looks like the gradle plugin hasn't been uploaded to the gradle plugin repository. This means that the snippet to use the plugin in the README doesn't work as well because gradle fails to find the plugin.

**Comment by mtdowling** [comment]
Yeah, sorry about that. We haven't yet published artifacts yet. We are taking care of a few other tasks before that, but we'll publish artifacts to Maven and Gradle early next week.

**Comment by jpmartin2** [comment]
Great! In the mean time, I was able to things working by building to the local maven repository, which just took a little bit of fiddling with maven on my part since I hadn't done that before.

**Comment by kstich** [comment]
[Smithy's artifacts are now available in Maven Central](https://search.maven.org/search?q=g:software.amazon.smithy).

[The Smithy Gradle Plugin is now available through the Gradle Plugin Portal](https://plugins.gradle.org/plugin/software.amazon.smithy).
