### ISSUE TITLE
Example of building the service side using smithy?

### ISSUE THREAD

**Issue by Johnlon** [awslabs/smithy#1060]
Can't find any demo or example or anything useful here or on the internet.

Am I missing something?

Please provide a ref if one is known.

Thanks

**Comment by mtdowling** [comment]
There's work being done in TypeScript and Rust, but neither are well documented or beta quality yet from what I understand: https://github.com/awslabs/smithy-typescript/tree/main/smithy-typescript-ssdk-libs and https://github.com/awslabs/smithy-rs/tree/main/codegen-server
