### ISSUE TITLE
What is the server behavior for deserializing `httpQueryParams` when multiple values appear for the same key?

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1071]
> The httpQueryParams trait can be applied to structure members that target a map of string, or a map of list/set of string.

When it targets a map of strings, what should a server implementation deserialize to when encountering multiple values for the same query key param? Should it pick the first value or the last one in the query string? The docs don't specify a behavior.

There are also no protocol tests.

**Comment by adamthom-amzn** [comment]
There's no defined behavior. The current server implementation is, I believe, as follows:

- for `@httpQuery` scalar members, the first value is taken
- for `@httpQueryParams` with scalar values, the last value is taken

**Comment by adamthom-amzn** [comment]
As we don't have a way to add protocol tests for SHOULDs yet (though this made us think we, uh, should), right now all I can offer is a documentation update.

**Comment by david-perez** [comment]
> As we don't have a way to add protocol tests for SHOULDs yet

@adamthom-amzn What mechanism did you have in mind? I was thinking that having separate test suites under `smithy-aws-protocol-tests/model/` for SHOULDs should suffice.
