### ISSUE TITLE
Allow identifier property to be annotated as create-only

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/smithy#1079]
Whenever we are receiving a resource identifier as input from user, the implicit binding resolution throws the following error:
> This operation is bound as a collection operation on the `smithy.example#Forecast` resource, but it improperly binds all of the identifiers of the resource to members of the operation input.

<details>
  <summary>Original Smithy model</summary>

```
namespace smithy.example

string ForecastName
document WeatherData

resource Forecast {
    identifiers: {
        forecastName: ForecastName,
    },
    create: CreateForecast,
    read: ReadForecast,
}

operation CreateForecast {
    input: CreateForecastInput,
    output: ForecastOutput
}

@input
structure CreateForecastInput {
    @required
    forecastName: ForecastName,
}

@readonly
operation ReadForecast {
    input: ReadForecastInput,
    output: ForecastOutput
}

@input
structure ReadForecastInput {
    @required
    forecastName: ForecastName,
}

structure ForecastOutput {
    @required
    forecastName: ForecastName,

    @required
    weather: WeatherData,
}
```

</details>

We would like to apply a trait to CreateForecastInput#forecastName so that is marked as [create-only](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html#schema-properties-createonlyproperties). Therefore, the implicit binding as well as the CloudFormation resource can be resolved correctly. Otherwise, the workaround provided below has the side effect of changing the identifier in the CloudFormation type.

<details>
  <summary>Temporary workaround</summary>

```
namespace smithy.example

use smithy.api#resourceIdentifier

string ForecastName
document WeatherData

resource Forecast {
    identifiers: {
        forecastId: ForecastName,
    },
    create: CreateForecast,
    read: ReadForecast,
}

operation CreateForecast {
    input: CreateForecastInput,
    output: ForecastOutput
}

@input
structure CreateForecastInput {
    @required
    forecastName: ForecastName,
}

@readonly
operation ReadForecast {
    input: ReadForecastInput,
    output: ForecastOutput
}

@input
structure ReadForecastInput {
    @required
    @resourceIdentifier("forecastId")
    forecastName: ForecastName,
}

structure ForecastOutput {
    @required
    forecastName: ForecastName,

    @required
    weather: WeatherData,
}
```

</details>

**Comment by mtdowling** [comment]
> Whenever we are receiving a resource identifier as input from user, the implicit binding resolution throws the following error:
>> This operation is bound as a collection operation on the smithy.example#Forecast resource, but it improperly binds all of the identifiers of the resource to members of the operation input.

If you want to provide the identifiers of a resource, it needs to be bound to the resource using a `put` lifecycle rather than a `create`.

```
resource Forecast {
    identifiers: {
        forecastName: ForecastName,
    },
    // not this // create: CreateForecast
    put: CreateForecast, // < this
    read: ReadForecast,
}
```

If you make that change, does it fix the CloudFormation issue?

**Comment by eduardomourar** [comment]
The CloudFormation issue is resolved with your suggestion while also using the `@noReplace` trait. Thanks!

You can see a better example including an update operation (which is closer to our specific use-case):
<details>
  <summary>Smithy model using put</summary>

```
namespace smithy.example

use aws.cloudformation#cfnResource
use aws.protocols#restJson1
use smithy.api#noReplace
use smithy.api#resourceIdentifier

@restJson1
service Weather {
  version: "2022-01-01",
  resources: [Forecast]
}

string ForecastName
document WeatherData

@noReplace
@cfnResource
resource Forecast {
    identifiers: {
        forecastName: ForecastName,
    },
    put: CreateForecast,
    read: ReadForecast,
    update: UpdateForecast,
}

@idempotent
@http(uri: "/forecast", method: "POST")
operation CreateForecast {
    input: CreateForecastInput,
    output: ForecastOutput
}

@input
structure CreateForecastInput {
    @required
    forecastName: ForecastName,
}

@readonly
@http(uri: "/forecast", method: "GET")
operation ReadForecast {
    input: ReadForecastInput,
    output: ForecastOutput
}

@input
structure ReadForecastInput {
    @required
    forecastName: ForecastName,
}

@idempotent
@http(uri: "/forecast", method: "PUT")
operation UpdateForecast {
    input: UpdateForecastInput,
    output: ForecastOutput
}

@input
structure UpdateForecastInput {
    @required
    forecastName: ForecastName,
}

structure ForecastOutput {
    @required
    forecastName: ForecastName,

    @required
    weather: WeatherData,
}
```

</details>

If we are still using HTTP POST, I believe it would be more ergonomical if the create operation could be annotated instead of passing in the `put`  To me personally, I see an upsert (update+create) operation making more sense in the put lifecycle.

I will leave this open until I have some feedback from the changes in our Smithy models.

**Comment by gosar** [comment]
The basic difference between `create` and `put` lifecycles (don't confuse `put` lifecycle with `PUT` http binding) is whether resource id is provided by client or server.

If your use case for resource creation is client provided resource id, then you'd have a `put` lifecycle operation for `CreateForecast`, likely as HTTP `POST`.

If your use case has upsert semantics too, you'd have a `put` lifecycle operation and maybe you call it `PutForecast`, likely as HTTP `PUT`.

If you don't have upsert, then a `put` lifecycle operation `CreateForecast` with `noReplace` and `update` lifecycle operation `UpdateForecast`, where `CreateForecast` uses `POST` and `UpdateForecast` uses `PUT` seems like the reasonable modelling.

So your model seems reasonable for your use case. (maybe you could consider binding forecastName in the URI, like `/forecast/{forecastName}`.

Feel free to reopen if you have any follow ups.
