### ISSUE TITLE
Make `httpResponseCode` be coupled with `required`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1098]
Currently, this is valid (taken from the [restJson1 protocol tests](https://github.com/awslabs/smithy/blob/887ae4f6d118e55937105583a07deb90d8fabe1c/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy)):

```smithy
@idempotent
@http(uri: "/HttpResponseCode", method: "PUT")
operation HttpResponseCode {
    output: HttpResponseCodeOutput
}

structure HttpResponseCodeOutput {
    @httpResponseCode
    Status: Integer
}
```

How should a server behave when `Status` is not provided? The [spec](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpresponsecode-trait) does not mention. Should it fall back to 200? In our Rust sSDK implementation, we are currently failing to serialize the response.

I think `httpResponseCode` without `required` should not be allowed, since status code cannot be omitted from the HTTP response as per the RFC.

**Comment by JordonPhillips** [comment]
> How should a server behave when Status is not provided?

You use whatever is set on the `http` trait.

**Comment by jjant** [comment]
@kstich @JordonPhillips regarding the [`RestJsonHttpResponseCodeDefaultsToModeledCode`](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy#L66-L70) test, isn't the `code` missing in the [operation's `@http` trait](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy#L12)?

**Comment by kstich** [comment]
[The `code` value of the `@http` trait defaults to 200 if not provided](https://awslabs.github.io/smithy/2.0/spec/http-bindings.html#http-trait)
