### ISSUE TITLE
`HttpMalformedRequestDefinition.getUri()` returns `Optional<String>`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1102]
The spec says [`uri` of `HttpMalformedRequestDefinition` is **required**](https://awslabs.github.io/smithy/1.0/spec/http-protocol-compliance-tests.html#httpmalformedrequestdefinition).

However, `HttpMalformedRequestDefinition.getUri()` returns `Optional<String>`:

https://github.com/awslabs/smithy/blob/887ae4f6d118e55937105583a07deb90d8fabe1c/smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestDefinition.java#L83-L85

This is in contrast to `HttpRequestTestCase.getUri()`, which returns `String`:

https://github.com/awslabs/smithy/blob/887ae4f6d118e55937105583a07deb90d8fabe1c/smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestCase.java#L65-L67

**Comment by JordonPhillips** [comment]
Yep that's not great. Unfortunately we can't change the type signature, but I added a pr to introduce a new non-optional getter.
