### ISSUE TITLE
Make `httpResponseCode` not worked with `httpError`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1105]
The following Smithy model builds without any warnings:

```smithy
$version: "1.0"

namespace com.amazonaws.simple

use aws.protocols#restJson1

@restJson1
@title("SimpleService")
service SimpleService {
    operations: [
        AnOperation,
    ],
}

@http(uri: "/operation", method: "GET")
operation AnOperation {
    input: AnOperationInput,
    output: AnOperationOutput,
    errors: [MyError]
}

structure AnOperationInput {
    @httpResponseCode
    responseCode: Integer
}

structure AnOperationOutput { }

@error("client")
@httpError(404)
structure MyError {
    @httpResponseCode
    responseCode: Integer
}
```

I'd expect it to be fail with errors:
1. ~[The spec](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpresponsecode-trait) says `httpResponseCode` is ignored if applied to operation input member. Why not enforce this by failing the build? It's clearly an error by the user.~
2. What response code should `MyError` set? Does the dynamic `httpResponseCode` one take precedence over the static `httpError` one if provided? I'd prefer it if [we made `httpResponseCode` coupled with `required`](https://github.com/awslabs/smithy/issues/1098), and outright rejected `httpResponseCode` applied to error structure members.

**Comment by mtdowling** [comment]
The spec is clear here:
> httpResponseCode is ignored when resolving the HTTP bindings of an operation's input structure. 

There are various traits in Smithy that only have effect contextually, and forbidding them makes it so structures aren't reusable. Just ignore the trait if it isn't used as a top-level output member. We could only forbid this trait if the structure is marked as `@input`.

**Comment by david-perez** [comment]
> and forbidding them makes it so structures aren't reusable

Hadn't thought about this.

> We could only forbid this trait if the structure is marked as @input.

It'd be a nice improvement.

---

I've amended the issue title in case you want to tackle the second item.

**Comment by mtdowling** [comment]
That sounds fine with me and would only be a selector change in the prelude and spec change. Can you make that change?

**Comment by syall** [comment]
The `@httpResponseCode` is no longer allowed to applied to `@input` structures, and the spec has been updated to clarify that `@httpResponseCode` will only affect HTTP bindings of output structures (#1359).
