### ISSUE TITLE
Server behavior with `httpResponseCode` outside valid range

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1116]
As of now, [`httpResponseCode` can only be applied to `integer` shapes](https://github.com/awslabs/smithy/issues/1115).

What should the behavior of a server implementation be when it attempts to serialize as an HTTP response code a value outside the 100-999 range? In the Rust sSDK we simply fail to serialize the response, but perhaps another behavior is desired (e.g. [falling back](https://github.com/awslabs/smithy/issues/1098#issuecomment-1051019501) to the `http` trait) .

**Comment by mtdowling** [comment]
IMO this seems like an HTTP spec thing and not a Smithy thing that needs to be explicitly documented in Smithy. I recommend failing to send the response.

**Comment by david-perez** [comment]
@mtdowling  Why shouldn't it be explicitly documented? It's a source of possible discrepancies among server implementations.

**Comment by mtdowling** [comment]
It's up to the server to set the httpResponseCode. It's not an arbitrary value, so it seems overly in the weeds to talk about this in the Smithy spec (and it's already covered in the HTTP, there's no need to repeat this in Smithy's spec). The client reads the value of a member marked with this trait to know what the HTTP status code returned by the server was.
