### ISSUE TITLE
Making `enum` exclusive constraint trait

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1121]
Does it make sense to allow `enum` trait to coexist with `length` or `pattern`? I don't think so. In any case, the values of the enum are not constrained by the other two traits; this model builds fine:

```smithy
$version: "1.0"

namespace com.amazonaws.simple

use aws.protocols#restJson1

@restJson1
@title("SimpleService")
service SimpleService {
    operations: [
        AnOperation,
    ],
}

@http(uri: "/operation", method: "GET")
operation AnOperation {
    input: AnOperationInput,
    output: AnOperationOutput,
}

structure AnOperationInput {
    enumMember: MyEnum
}

structure AnOperationOutput {
}

@enum([
    {
        value: "t2.nano",
        name: "T2_NANO",
    },
    {
        value: "t2.micro",
        name: "T2_MICRO",
    },
    {
        value: "m256.mega",
        name: "M256_MEGA",
    }
])
@length(min: 1, max: 3)
@pattern("\\d+")
string MyEnum
```

**Comment by JordonPhillips** [comment]
FWIW we're making enums shapes in v2, you could very easily add `:not(enum)` to their selectors

**Comment by mtdowling** [comment]
While I agree with the spirit of this issue, I don't think like it's worth the risk of breaking existing models (particularly the tens of thousands inside of AWS). It's a stretch, but a use case for mixing enum and pattern/length might be that a team wants to restrict how future enum values are modeled by the service team -- they can use length and pattern to constrain it in the future even if it doesn't make sense to enforce server-side.

Given enums are going to be promoted to shapes in IDL v2, I think this change has more risk than reward.

**Comment by david-perez** [comment]
The EBS model has this:

https://github.com/awslabs/smithy-rs/blob/e1e9a29d5db1330eb51c1e84e5c6c3acb9b4f65e/aws/sdk/aws-models/ebs.json#L1195-L1217

> they can use length and pattern to constrain it in the future even if it doesn't make sense to enforce server-side.

Then Smithy CLI should enforce this, not each code generator.
