### ISSUE TITLE
Please provide a full example how to use Smithy

### ISSUE THREAD

**Issue by nagyf** [awslabs/smithy#1169]
I've been trying to setup Smithy for a very simple project for 2 hours now, and I'm starting to give up.

In my opinion the official [Quick Start Guide](https://awslabs.github.io/smithy/quickstart.html) should include a full example for **using** Smithy, not just for setting up the model and the Gradle config. 

I don't understand how to generate Java code based on the Smithy models. I've generated an empty Java project, set up Smithy with a very simple model based on the Quickstart Guide, and when I run gradle build it builds my model without issue. However, I can't find the generated classes anywhere.

Gradle output:
```
...

Building Smithy model sources: [/home/nagyf/dev/microservice/svc-user/model]
Loading Smithy configs: [/home/nagyf/dev/microservice/svc-user/smithy-build.json]
Validation result: 0 ERROR(s), 0 DANGER(s), 0 WARNING(s), 0 NOTE(s)
Validated 174 shapes in model
Completed projection source (174 shapes): /home/nagyf/dev/microservice/svc-user/build/smithyprojections/svc-user/source
Smithy built 1 projection(s), 3 plugin(s), and 4 artifacts

...
```

My expectation is that after running gradle build I should be able to find the generated Java classes in the generated-sources folder. The only thing I could find is the `smithyprojections` folder, but that does not contain any sources.

Do I need to setup generating Java classes based on the model separately? If yes, where is the documentation for that?
After setting up everything using the Quickstart Guide, how can I actually use the model? How can I generate the service?

**Comment by adamthom-amzn** [comment]
Talked to Ferenc online - we don't have any Java code generators available yet. All of our pre-release code generators are discoverable at https://awslabs.github.io/smithy/implementations.html#code-generators
