### ISSUE TITLE
`uniqueItems` is deprecated but docs are outdated and no warnings are emitted

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1182]
`UniqueItemsTrait` was marked `@Deprecated` and the RST source calls this out [since August 2021](https://github.com/awslabs/smithy/commit/6084e161235994b6a3a7c841589e039aee178a8c), yet:

* the below model does not emit any warnings; and
* the [currently built docsite doesn't show this warning](https://awslabs.github.io/smithy/1.0/spec/core/constraint-traits.html#uniqueitems-trait).

```smithy
$version: "1.0"

namespace com.amazonaws.simple

use aws.protocols#restJson1

@restJson1
service SimpleService {
    operations: [
        AnOperation,
    ],
}

@http(uri: "/operation", method: "GET")
operation AnOperation {
    input: AnOperationInputOutput,
    output: AnOperationInputOutput,
}

structure AnOperationInputOutput {
    list: MyList
}

@uniqueItems
list MyList {
    member: String
}
```

**Comment by mtdowling** [comment]
Yeah that should emit a warning.

looks like the docs are busted because the warning admonition is missing a colon “.. warning:”

**Comment by mtdowling** [comment]
Your example model and this model does emit a warning:

```
$version: "1.0"

namespace smithy.example

@uniqueItems
list MyList {
    member: String
}
```

Output:

```
[WARNING] smithy.example#MyList: This shape applies a trait that is deprecated: smithy.api#uniqueItems, The uniqueItems trait has been deprecated in favor of using sets. | DeprecatedTrait
```
