### ISSUE TITLE
Recursive shape definitions restriction not restrictive enough

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1183]
The [section on recursive shapes](https://awslabs.github.io/smithy/1.0/spec/core/model.html#recursive-shape-definitions) cites only one restriction:

> Smithy allows for recursive shape definitions with the following constraint: the member of a list, set, or map cannot directly or transitively target its containing shape unless one or more members in the path from the container back to itself targets a structure or union shape.

The following model does not violate this restriction:

```smithy
$version: "1.0"

namespace com.amazonaws.simple

use aws.protocols#restJson1

@restJson1
@title("SimpleService")
service SimpleService {
    operations: [
        AnOperation,
    ],
}

@http(uri: "/operation", method: "GET")
operation AnOperation {
    input: RecursiveShapesInputOutput,
    output: RecursiveShapesInputOutput,
}


structure RecursiveShapesInputOutput {
    nested: RecursiveShapesInputOutputNested1
}

structure RecursiveShapesInputOutputNested1 {
    @required
    recursiveMember: RecursiveShapesInputOutputNested2
}

structure RecursiveShapesInputOutputNested2 {
    @required
    recursiveMember: RecursiveShapesInputOutputNested1,
}
```

However, we can't generate any reasonable code for it, since the data structure is infinitely mutually recursive.

**Comment by JordonPhillips** [comment]
Without any ability to have mutually recursive shapes, you'd not be able to build dynamodb, so we cannot make this change. For reference, the following AWS services currently have mutually recursive structures:

```
[
    "RDS Data",
    "Lex Runtime V2",
    "kendra",
    "DynamoDB",
    "FSx",
    "EMR",
    "Timestream Query",
    "SSM",
    "SageMaker",
    "WAFV2",
    "AmplifyUIBuilder",
    "Cost Explorer",
    "Organizations",
    "DynamoDB Streams",
    "IoTTwinMaker",
    "EMR containers"
]
```

**Comment by mtdowling** [comment]
Those services have mutually recursive shapes that are required?
