### ISSUE TITLE
Remove httpResponseCode from OpenAPI document output

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/smithy#1199]
Whenever attaching the [httpResponseCode trait](ttps://awslabs.github.io/smithy/1.0/spec/core/http-traits.html?highlight=httpresponsecode#httpresponsecode-trait) to a shape, I would expect them to be removed from the OpenAPI document. Instead, they are put as a property in the output, which is causing confusion to the consumer of our APIs.

**Comment by mtdowling** [comment]
Yeah, that's a good idea. It has no meaning in the OpenAPI model, so we should remove it.

**Comment by srchase** [comment]
When configured with the `restJson1` protocol, this property is not being set.
```
@http(code: 200, method: "POST", uri: "/echo",)
operation echo {
    input: EchoInput,
    output: EchoOutput,
    errors: [InvalidInputException]
}

structure EchoOutput {
    string: String,

    foo: String,

    bar: Integer,

    @httpResponseCode
    statusCode: StatusCode
}

integer StatusCode

@httpError(400)
@error("client")
structure InvalidInputException {
    message: String,
}
```

Results in:
```
"echoResponseContent": {
    "type": "object",
    "properties": {
        "string": {
            "type": "string"
        },
        "foo": {
            "type": "string"
        },
        "bar": {
            "type": "number",
            "format": "int32",
            "nullable": true
        }
    }
}
```
Could you supply the model and protocol you're using to reproduce this issue?

**Comment by eduardomourar** [comment]
We are also using `restJson1` protocol. After updating to the latest Smithy tools, the property is not appearing in the OpenAPI definition anymore. Thanks!
