### ISSUE TITLE
Removing an enum variant is not a backwards-compatible change

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1204]
Does Smithy warn against removing [enum](https://awslabs.github.io/smithy/1.0/spec/core/constraint-traits.html#enum-trait) variants from a model? I don't think [the docs on "Evolving Models"](https://awslabs.github.io/smithy/1.0/guides/evolving-models.html#evolving-models) cover it.

Removing an enum variant is a backwards-incompatible change: an old client's request containing a removed enum variant will get rejected by the server.

**Comment by kstich** [comment]
[The `ChangedEnumTrait` evaluator](https://github.com/awslabs/smithy/blob/main/smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java) in smithy-diff emits an error level diff event if a value is removed from an enum.

We should add a general note to the "Evolving Models" page about using smithy-diff to detect breaking changes, as detailing all the breaking changes possible for every trait would be overwhelming for that page. However, the `enum` and `intEnum` shape types should get an entry on the page for IDL v2.
