### ISSUE TITLE
smithy to grpc/proto

### ISSUE THREAD

**Issue by hugobellomusto** [awslabs/smithy#1221]
I wonder if you are planing to generate grpc/proto from smithy.

As far as I can understand, in [this post](https://news.ycombinator.com/item?id=27082454) @mtdowling is suggesting that smithy is something parallel to grpc.

Maybe something like [smithy streaming](https://awslabs.github.io/smithy/1.0/spec/core/stream-traits.html#event-streams) could be used to generate grpc/proto, but I couldn't find any reference to something like that.

Thanks!

**Comment by mtdowling** [comment]
No, we don't currently have plans to convert Smithy to or from Protobuf. They're different models that operate at the same layer of abstraction but with diverging feature sets. They even have different semantics around what is and isn't a backward compatible change. Smithy is open source though, so anyone can build converters to other formats.
