### ISSUE TITLE
For some pattern values, are we able to make them constant and share between files?

### ISSUE THREAD

**Issue by codingswag998** [awslabs/smithy#1242]
We are working on defining some smithy models and found that some regEx pattern can be reused. We would like to know if we can make those pattern constant and share between files?

**Comment by mtdowling** [comment]
You can define a string shape, apply the pattern trait to it, and reference it from members of structures, lists, etc.

    @pattern(“example”)
    string MyString

    list MyStrings {
        member: MyString
    }

You can refer to this shape from any other file as long as the model that defines the shape is included in the files you’re building (eg classpath in Gradle or smithy-build.json includes).
