### ISSUE TITLE
Recursive shape definitions restriction not restrictive enough part 2

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1247]
This is a follow-up on https://github.com/awslabs/smithy/issues/1183.

I guess the phrase "unless one or more members in the path from the container back to itself targets a structure or union shape" needs to be tweaked to mention that the union shape must have more than one member (?).

You can otherwise have recursive unions:

```smithy
structure AnOperationInputOutput {
    listShape: ListShape
}

list ListShape {
    member: UnionShape
}

union UnionShape {
    member: ListShape
}
```

But even if you tweaked that sentence, you could still have, more simply:

```smithy
union RecursiveUnion {
    member: RecursiveUnion
}
```

So I guess a better way to disallow these is to add another bullet point mentioning that union shapes that refer back to themselves must have more than one member?

**Comment by david-perez** [comment]
I looked at the PR. I think it only addresses direct recursion. This should also be deemed invalid right?

```smithy
union RecursiveUnion {
    a: RecursiveUnion2,
}

union RecursiveUnion2 {
    b: RecursiveUnion,
}
```

**Comment by mtdowling** [comment]
Oh yeah, you’re right. We can follow up here to do a similar path traversal we do with structures.
