### ISSUE TITLE
Ambguity in the Smithy IDL grammar

### ISSUE THREAD

**Issue by hlbarber** [awslabs/smithy#1249]
One example of an ambiguity in the grammar is within `shape_section` given in the [Smithy IDL specification](https://github.com/awslabs/smithy/blob/df456a514f72f4e35f0fb07c7e26006ff03b2071/docs/source/1.0/spec/core/idl.rst) under "Smithy IDL ABNF" -> "Shapes".

```
shape_section : [`namespace_statement` [`use_section`] [`shape_statements`]]
use_section : *(`use_statement`)
```

Is ``[`use_section`]`` empty or is it populated with an empty ``*(`use_statement`)``?

This places Smithy IDL outside of a large class of grammars (see page 4 of [Miscellaneous Parsing](https://web.stanford.edu/class/archive/cs/cs143/cs143.1128/handouts/150%20Miscellaneous%20Parsing.pdf)).

An example of where this is a problem is when trying to implement the grammar in [lalrpop](https://github.com/lalrpop/lalrpop) which will complain when we try to implement the following

```lalrpop
use_section = use_statement*;
pub shape_section = use_section?;
```

A similar conflict is described in [this issue](https://github.com/lalrpop/lalrpop/issues/271).

The ambiguity around ``[`use_section`]`` can be resolved by making it non-optional or changing `use_section` to ``1*(`use_statement`)``.

* Should we attempt to resolve syntax ambiguities?
* Should we document how to resolve conflicts?
* Is it permissible to change the grammar if it does not change the language/semantics?
* Should we document the formal properties of the grammar?

_Disclaimer: I'm not an expert in language theory, please be skeptical of my claims and correct me where needed._

**Comment by mtdowling** [comment]
I don't think this is ambiguous, but sure the `[` and `]` around `use_section` is unnecessary since `*(user_statement)` is already 0 or more.

And yes, we can change the grammar if it's a bug fix. Please feel free to send us a PR!
