### ISSUE TITLE
Support for generation of JSON Schema version 2020-12

### ISSUE THREAD

**Issue by ZackKanter** [awslabs/smithy#1252]
The JSON Schema generator currently only [supports Draft 7](https://github.com/awslabs/smithy/blob/main/smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java#L41-L42). 

It would be great if it could also support [`2020-12`](https://json-schema.org/specification-links.html#published-drafts), which is the version we need. I would imagine others may need `2019-09`.

**Comment by ZackKanter** [comment]
That would be fantastic.

**Comment by ZackKanter** [comment]
Just checking back on this!

**Comment by handrews** [comment]
JSON Schema spec co-author here: I definitely advise skipping 2019-09.  It has no advantages over 2020-12 and several disadvantages.  Plus 2020-12 is used by OpenAPI 3.1 which is another driver of adoption for this specific draft.
