### ISSUE TITLE
Should clients reject responses with `set`s with duplicate elements?

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1266]
If a client receives a response, that, upon deserialization, results in data for a `set` shape that contains duplicate values, should a client reject it?

Servers do reject requests:

https://github.com/awslabs/smithy/blob/c8ce65a2bcc0264f3aeeb9db096564e0491a8786/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-set.smithy#L15-L36

**Comment by adamthom-amzn** [comment]
No. Clients rejecting responses is lossy (it prevents you from knowing about state changes that actually happened).

**Comment by david-perez** [comment]
Under what circumstances should clients reject responses? Only upon deserialization errors (like malformed JSON)? I'm thinking if having `httpMalformedResponseTests` would be a useful feature..

**Comment by adamthom-amzn** [comment]
Yes, in general a client should do everything in its power to render a response from the server. Malformed JSON (or a non-JSON response) are the only cases I can think of where you should reject a response.

**Comment by mtdowling** [comment]
We deprecated sets and treating them exactly like `@uniqueItems`. They'll be removed in IDL v2. In that sense, it's a constraint trait, clients shouldn't evaluate constraint traits (for the most part), so clients shouldn't care if there are duplicates in responses.

**Comment by david-perez** [comment]
> Malformed JSON (or a non-JSON response) are the only cases I can think of where you should reject a response.

I think there's another category of warranted response rejections by the client: number conversions. [Technically not malformed JSON](https://twitter.com/hdevalence/status/1557083235338711041). But it's best for the client to reject a number that doesn't fit in the Smithy modeled type than to attempt an e.g. double to single-precision float conversion, or a floating point into an integral type conversion, when the receiver type cannot fit the value. Not rejecting could lead to very hard to identify logic bugs.

I think an `httpMalformedResponseTests` suite would thus be useful just for this case.

I identified this category of errors when trying to pass `httpMalformedRequestTests` in the server, but also made the change for clients in smithy-rs in https://github.com/awslabs/smithy-rs/pull/1274.
