### ISSUE TITLE
smithy-openapi module : Invalid format set on type number

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1274]
When Smithy is converted to Open Api , if useIntegerType is not set , the field will be of type number.
The format is set to int32 for IntegerShape, int64 for LongShape .. regardless of if the field type is number or integer.
[Source](https://github.com/awslabs/smithy/blob/5c319a22c177dd89989c27c435c12cf64c69550b/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java#L79)
This is incorrect according to the OAS which specifies that int32,int64 are not valid format types of Number 
https://swagger.io/specification/#data-types

**Comment by mtdowling** [comment]
Fixed in https://github.com/awslabs/smithy/pull/1299. Will go out in the next release.
