### ISSUE TITLE
dynamically representing field-name in smithy 

### ISSUE THREAD

**Issue by SOPHIA2401** [awslabs/smithy#1282]
### Problem Faced
While writing a response structure for a smithy model. I wanted to dynamically represent one of the field names as the name of the index that the model response is returning. 

### Example:
Below is the model defined for `Get /{index}/_settings` API.
#### Request Structure
```
structure GetSettingsIndexInput {
    
    @httpLabel
    @required
    index: IndexName,

    @httpQuery("allow_no_indices")
    allow_no_indices: Boolean,

    @httpQuery("expand_wildcards")
    expand_wildcards: ExpandWildcards,

    @httpQuery("flat_settings")
    flat_settings: Boolean,

    @httpQuery("include_defaults")
    include_defaults: String,

    @httpQuery("ignore_unavailable")
    ignore_unavailable: Boolean,

    @httpQuery("local")
    local: Boolean,

    @httpQuery("master_timeout")
    master_timeout: Time,
}
```

#### Required Response structure

```
structure GetSettingsIndexOutput {

   <IndexName>: UserDefinedMap

}
```
`<IndexName>` in response structure must match with the index value specified in request structure.

**Comment by mtdowling** [comment]
I don't see how this could work in in Smithy (I'd also suggest a different API design if you can control it). If this is needed, it can be implemented using a nested map of some kind or possibly a document type if the different values for different keys aren't all homogeneous (the document type could be nested or set as the `@httpPayload`).
