### ISSUE TITLE
Missing dot operator [.] support in Smithy model.

### ISSUE THREAD

**Issue by SOPHIA2401** [awslabs/smithy#1283]
While defining the request/response structure for a smithy model, I wanted to write few field names using a dot operator `"."`. 

#### For example: 
```
structure GetCatIndicesWithIndexOutput {
   ...
    docs.count: String
   ...

}
```
However an error is returned when converting Smithy models with fields defined by the dot operator to JSON-models.

#### Error
```
49 |   docs.count: String, 
   |     ^
   = Parse error at line 49, column 9 near `.c`: Expected: ':', but found '.'


Validation result: 1 ERROR(s), 0 DANGER(s), 0 WARNING(s), 0 NOTE(s)
```

**Comment by kstich** [comment]
[A `.` is not a valid character for a member name, or any other identifier outside of a namespace.](https://awslabs.github.io/smithy/1.0/spec/core/model.html#shape-id) If you're looking to serialize a member into a JSON document with a key name containing a `.`, [you can use the `@jsonName` trait](https://awslabs.github.io/smithy/1.0/spec/core/protocol-traits.html#jsonname-trait).
