### ISSUE TITLE
Tests where the URI contains spaces

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1315]
There are tests like [this one](https://github.com/awslabs/smithy/blob/b45b802d4257aaa9becef0996c1ce93531fbf5e7/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-path.smithy#L118) where the URI contains spaces. Is this a valid test? We (smithy-rs) fail when parsing the test, but the failure being tested expects a SerializationException.

**Comment by mtdowling** [comment]
That looks like a bug in the test case
