### ISSUE TITLE
Issues with the ABNF grammar for Smithy IDL

### ISSUE THREAD

**Issue by jamesls** [awslabs/smithy#1324]
I was working through the ABNF grammar for the Smithy IDL and
encountered several minor issues.

### Some rules MUST require at least one whitespace

A structure statement is defined as:

```
structure_statement = "structure" ws identifier ws shape_members
```

And the `ws` rule is defined as:

```
ws = *(sp / newline / comment) ; whitespace
```

which matches zero or more whitespace.  This means something like this is a valid
`structure_statement`:

```
structureMyStructure{}
```

### Some rules should explicitly allow newlines

The `node_string_value` rule does not allow for new lines in the `quoted_char`
rule.  For example, the Smithy parser accepts this as valid:

```
@documentation("""

    """)
string NewlineString
```

But the grammar for `text_block` is:

```
text_block =
    three_dquotes br *quoted_char three_dquotes

three_dquotes =
    DQUOTE DQUOTE DQUOTE

quoted_char =
    %x20-21        ; space - "!"
  / %x23-5B        ; "#" - "["
  / %x5D-10FFFF    ; "]"+
  / escaped_char
  / preserved_double

```

These rules do not permit any newline characters (`%x0A / %x0D.0A`)
after the initial `three_dquotes br` new line.

### `trait_body_value` can be optional

A `trait_body` must contain a `trait_body_value`:

```
trait =
    "@" shape_id [trait_body]

trait_body =
    "(" ws trait_body_value ws ")"

trait_body_value =
    trait_structure / node_value
```

However, the Smithy parser excepts an empty `trait_body_value`,

```
structure GetCityInput {
    @required()
    cityId: CityId,
```

<br />

*(the remaining stuff is nit-picky and maybe just worth calling out where
you deviate from RFC 5234 instead of fixing)*

#### Rule names use underscores

From [Section 2.1 or RFC 5234](https://datatracker.ietf.org/doc/html/rfc5234#section-2.1):

> The name of a rule is simply the name itself, that is, a sequence of
   characters, beginning with an alphabetic character, and followed by a
   combination of alphabetics, digits, and hyphens (dashes).

Note that underscores are not allowed.  This is also shown in the ABNF of ABNF
in [Section 4](https://datatracker.ietf.org/doc/html/rfc5234#page-10):

```
         rulelist       =  1*( rule / (*c-wsp c-nl) )

         rule           =  rulename defined-as elements c-nl
                                ; continues if next line starts
                                ;  with white space

         rulename       =  ALPHA *(ALPHA / DIGIT / "-")
```

I encountered this because I have tools that take as input a valid ABNF grammar
and were either failing or producing unexpected results.

#### Literal strings aren't case insensitive

From [Section 2.3](https://datatracker.ietf.org/doc/html/rfc5234#section-2.3):

> Literal text strings are interpreted as a concatenated set of
>    printable characters.
> 
>    NOTE:
> 
>       ABNF strings are case insensitive and the character set for these
>       strings is US-ASCII.
> 
>    Hence:
> 
>          rulename = "abc"
> 
>    and:
> 
>          rulename = "aBc"
> 
>    will match "abc", "Abc", "aBc", "abC", "ABc", "aBC", "AbC", and
>    "ABC".

Literal strings are used in the various statements for the `shape_body` rule,
e.g. `structure`, `resource`, etc.

**Comment by milesziemer** [comment]
Fixed by #1327
