### ISSUE TITLE
Increase support for the Accept header

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1332]
Some smithy clients and servers, such as in [Typescript](https://github.com/awslabs/smithy-typescript/blob/ac8fb3f406807bfd14a8f7be8d938377bde36189/smithy-typescript-ssdk-libs/server-common/src/accept.ts#L20), allow the Accept header to reflect HTTP's spec, by allowing `*/*` and `type/*`. The smithy spec allows neither of them. 

After discussing this change, it was proposed to:
* reflect the HTTP spec regarding the Accept header more closely, allowing `*`, but no q-factor weighting
* servers should not use Accept to do protocol selection and allow them to respond in any of the allowed (by the header's value) ways

**Comment by 82marbag** [comment]
Related issue in smithy-rs, where we follow more closely the smithy spec: https://github.com/awslabs/smithy-rs/issues/1544

**Comment by kstich** [comment]
Closed by #1365
