### ISSUE TITLE
Minor 2.0 doc fixes

### ISSUE THREAD

**Issue by iancaffey** [awslabs/smithy#1343]
Noticed a couple really minor things when skimming the 2.0 docs. Kinda nit-picky, but hope it's still helpful. :-)

[Homepage](https://github.com/awslabs/smithy/blob/main/docs/source-2.0/index.rst)
- `Foreast` -> `Forecast`
- Trailing comma too?

[JSON AST](https://github.com/awslabs/smithy/blob/main/docs/source-2.0/spec/json-ast.rst)
- Missing `properties` in the [resources table](https://github.com/awslabs/smithy/blob/main/docs/source-2.0/spec/json-ast.rst#resource-shape) (but it is present in the [service types](https://github.com/awslabs/smithy/blob/main/docs/source-2.0/spec/service-types.rst#resource) page) 

I can submit a PR for them if necessary, but I figured since it's a 2 character change and some copy/paste from another page, might be small enough to lump into any other docs changes being done by the Smithy team.

**Comment by syall** [comment]
Another small change needed in the migration guide: Smithy 2.0 example `$version` for still says `$1.0`.

- Reference: https://awslabs.github.io/smithy/2.0/guides/migrating-idl-1-to-2.html#remove-unsightly-commas

**Comment by srchase** [comment]
Fixed by #1343.
