### ISSUE TITLE
Should a request with no `Accept` be accepted when the operation does not model output?

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1376]
There is a protocol test testing that when `Accept` is set to the protocol's default response `Content-Type`, a request for an operation with no output is accepted:

https://github.com/awslabs/smithy/blob/69cc7ba87b62da026130876d3e306194f39759ee/smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy#L130-L143

I'm interested in the case when _no_ `Accept` header exists in the request. We should technically reject, because there is another test testing that `{}` is returned in the body in this case (although this test is only for modeled error responses).

https://github.com/awslabs/smithy/blob/69cc7ba87b62da026130876d3e306194f39759ee/smithy-aws-protocol-tests/model/restJson1/errors.smithy#L29-L47

However, it seems a bit too harsh to reject, especially since operations with no output are usually utilized for healthchecks (which might be performed by e.g. NLB), and the user then has to manually configure their healthchecks to use `*/*` (like curl does by default) or the protocol's default response content type in the `Accept` header.

**Comment by adamthom-amzn** [comment]
Why do you think you should technically reject? According to RFC 7231 [5.3.2](https://www.rfc-editor.org/rfc/rfc7231#section-5.3.2)

>    A request without any Accept header field implies that the user agent
   will accept any media type in response.  If the header field is
   present in a request and none of the available representations for
   the response have a media type that is listed as acceptable, the
   origin server can either honor the header field by sending a 406 (Not
   Acceptable) response or disregard the header field by treating the
   response as if it is not subject to content negotiation.

**Comment by david-perez** [comment]
My bad. I'm sorry, it's been a long day.
