### ISSUE TITLE
How to generate Java classes from the model definition using the Gradle plugin

### ISSUE THREAD

**Issue by gredditor** [awslabs/smithy#1390]
[Also asked in: https://github.com/awslabs/smithy-gradle-plugin/issues/61] 

In an attempt to introduce my company to automated code generation from service definitions, I am looking to get started with defining my APIs with Smithy and use the Gradle plugin to generate the Java code. I followed the complete example as described in https://awslabs.github.io/smithy/2.0/quickstart.html#complete-example

After running gradle build, it did generate the Jar but it does not contain any Java classes.

```
jar -tvf build/libs/smithy-example.jar
     0 Mon Sep 05 12:46:56 PDT 2022 META-INF/
    40 Mon Sep 05 12:44:26 PDT 2022 META-INF/MANIFEST.MF
     0 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/
    15 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/manifest
  2577 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/weather.smithy

```
The contents of my project files are exactly as shown in the complete example section. After running gradle build I expected it to generate the model classes and a client SDK for the service but that does not seem to be the case. Let me know what I am missing or if I completely misunderstood this project.

**Comment by gredditor** [comment]
Ping

**Comment by mtdowling** [comment]
We don't currently have any Java code generation for Smithy. It's something we're working on soon. You can see the list of known implementations here: https://awslabs.github.io/smithy/2.0/implementations.html

**Comment by avanideshpande** [comment]
"It's something we're working on soon" -> Do you have any ETA for when Java code generation might be available for Smithy?

**Comment by Askmecoding** [comment]
I do not see Java as supported language yet. Do you have any update for us? I am curious to know why is Java support still not added. Are there any challenges that we should be aware of if we go with own code generator option mentioned above?

**Comment by cmoher** [comment]
we are actively working on a smithy-java code generator.  However, we have not made the repo public yet.  Unfortunately, I can't provide a timeline just yet for when that will be.

**Comment by cmoher** [comment]
smithy-java is now publicly available in preview. https://github.com/smithy-lang/smithy-java
