### ISSUE TITLE
Mixin serialization - Guidance

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1408]
Is there an option in the Model Serializer to include all mixin members as part of the shape they are applied to
Currently the mixins will show up as a separate object 
```
"MyInput": {
      "type": "structure",
      "mixins": [
        {
          "target": "test#HasId
        }
      ],
      "members": {
        "first": {
          "target": "smithy.api.String",
        }
      }
      }
```

**Comment by mtdowling** [comment]
No, mixins form a graph and don't repeat the shapes that are mixed in to. You can flatten mixins, which copies members into the places they were mixed in, but it also removes mixins from the model.

For example:

```
use software.amazon.smithy.model.transform.ModelTransformer;
...
Model flattened = ModelTransformer.create().flattenAndRemoveMixins(model);
```

**Comment by yisraelU** [comment]
Thank you , I didnt know that Transformer existed .That solves my problem
