### ISSUE TITLE
Official AWS models?

### ISSUE THREAD

**Issue by pcolby** [awslabs/smithy#1423]
Hi, not sure this is the right place to ask, can't see anywhere better 🤷🏻 

If I understand correctly, this repo covers the Smithy project itself. And apart from some AWS-specific traits, etc, is not specific to AWS.

I also see that a number of AWS SDKs are built from AWS Smithy models, such as [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2/tree/main/codegen/sdk-codegen/aws-models) and [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models).  But these projects copy the AWS Models into their own repos, resulting in lots of different versions of the Models floating around the `awslabs` repos - some versions are hours old, some months.

So, my question is: where is the canonical source for the *current* AWS Models, that I can track for my own open-source projects?  I assume there's some internal AWS repo from which these SDKs get their updates - can that be made public? (if it's not already)

Thanks! 🙂

**Comment by AndrewFossAWS** [comment]
Unfortunately we do not share the models publicly. 

However the models from [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models) get updated regularly so they are fairly accurate.

**Comment by pcolby** [comment]
Thanks @AndrewFossAWS, that is unfortunate, but I will use [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models) for now as suggested.

That said, [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2/tree/main/codegen/sdk-codegen/aws-models) and [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models) seem to both stay up to date far more than any of the others I've looked at.  For interest, I normalised all of the model files in both (they use slightly different JSON formatting), and found only two small differences:

```diff
diff -br aws-sdk-go-v2/codegen/sdk-codegen/aws-models/iotsecuretunneling.json aws-sdk-js-v3/codegen/sdk-codegen/aws-models/iotsecuretunneling.json
241c241
<           "name": "IoTSecuredTunneling"
---
>           "name": "iotsecuredtunneling"
diff -br aws-sdk-go-v2/codegen/sdk-codegen/aws-models/mobile.json aws-sdk-js-v3/codegen/sdk-codegen/aws-models/mobile.json
73c73
<           "name": "AWSMobileHubService"
---
>           "name": "awsmobilehubservice"
```
This `"name"` is for the [`"aws.auth#sigv4"`](https://awslabs.github.io/smithy/1.0/spec/aws/aws-auth.html) trait, which "SHOULD match the `arnNamespace` property" (and is required to be applied in lowercase for V4 signatures) so the JS SDK is "more" right than Go in this case (Go's doesn't match the `arnNamespace`), but both are valid, as long as Go is lowercasing in the V4 signature code.  I'll mention it to the `aws-sdk-go-v2` project, but it is only a SHOULD, not a MUST, in the Smithy spec.

Cheers.

**Comment by irad100** [comment]
> Thanks for bringing this up. @pcolby
> 
> Just want to mention we do plan on creating a seperate repo specifically for AWS models in the future.

Is there an update about publishing AWS models?

**Comment by will-rippling** [comment]
@AndrewFossAWS any update on a separate repo for AWS smithy definitions?

**Comment by cmoher** [comment]
We have received a number of requests for a canonical source of Smithy models for AWS Services.   In 2025, we plan to provide a public GitHub repo with Smithy models that are updated regularly.  (I can't provide a more precise timeline at this time.)

**Comment by pcolby** [comment]
For anyone that comes across this issue, Amazon has just [officially announced](https://aws.amazon.com/blogs/aws/introducing-aws-api-models-and-publicly-available-resources-for-aws-api-definitions/) a "publicly available source of API models for [Amazon Web Services (AWS)](https://aws.amazon.com/)".

The new repo (and thus the answer to my original question) is: https://github.com/aws/api-models-aws 🎉
