### ISSUE TITLE
Add tags to documentation trait

### ISSUE THREAD

**Issue by kiiadi** [awslabs/smithy#1437]
**Feature Request**

Consider adding an optional `tag` (or similar) attribute to the `documentation` trait. Documentation on shapes may target different personas and it would be useful to be able to apply projection filters based on them. Simplest example would be when defining an SPI using Smithy - I want to be able to have documentation that is intended for SPI implementers, and separate documentation that is intended for API consumers.

Would love to be able to do something like:

```
@documentation("This documentation is intended for SPI implementers", tags: ["server"])
@documentation("This documentation is intended for API consumers", tags: ["client"])
structure MyShape { 
```

**Comment by mtdowling** [comment]
This couldn't be added backward compatibly. The way this would normally be done is by adding your own traits to specify documentation for each persona (e.g., `@spiDocumentation`).
