### ISSUE TITLE
How to describe a lookup either by a `Foo`, or a `Bar`

### ISSUE THREAD

**Issue by ShahOdin** [awslabs/smithy#1475]
Effectively, I want to have unions as Operation Inputs if we can have such a thing. This is what I tried:

```smithy
$version: "2.0"

namespace smithy4s.hello

@http(method: "POST", uri: "/lookup", code: 200)
operation LookupCustomer {
    input:= {
        @required
        id: LookupId
    }
    output: Customer,
}

string UserId
string CustomerId

union LookupId {
    @httpQuery("userId")
    customerId: UserId,

    @httpQuery("customerId")
    userId: CustomerId
}

@output
structure Customer {
    @required
    message: String
}
```

but I am getting:

> 'httpQuery' may only be applied to shapes that match the following selector: structure > member :test(> :test(string, number, boolean, timestamp), > list > member > :test(string, number, boolean, timestamp))

ie, it doesn't like me using unions. 

Looking at https://github.com/awslabs/smithy/issues/1112#issuecomment-1054445719 I am getting the impression it's not possible? quite disappointing really.

The above demonstrated an example of using query parameters to pass union input. Alternative use case is `/lookup/{lookupId}` where `lookupId` might be either say a 5 digits long number, or a 10 digits long number, ie legacy vs new Ids. So there would be an order in which you'd try to parse them and use whatever works. 

Guessing that can't be expressed in Smithy either?

**Comment by kstich** [comment]
The `httpQuery` and `httpLabel` traits are only effective when applied to members of the structures that are inputs to an operation at the top level. Inputs and outputs for operations must be structures to allow for safe, forwards compatible API evolution.

The `id` field you're trying to model as a union would be valid if left in the body, by removing the `httpQuery` trait. Otherwise, this operation seems like it could either overload the input `id` member as a label or be broken up in to one old, deprecated operation with the legacy id and one with the new id.

**Comment by ShahOdin** [comment]
Thanks @kstich 

> Otherwise, this operation seems like it could either overload the input id member as a label

Can you do that? Could you please give a minimal example of this?

**Comment by kstich** [comment]
It would just mean accepting both types of values for a singular `customerId` input string member in the model, and handling the difference in service behavior.

```
@http(method: "POST", uri: "/lookup/{customerId}", code: 200)
operation LookupCustomer {
    input:= {
        @required
        @httpLabel
        customerId: CustomerId // Service behavior allows this to be either type of Id
    }
    output: Customer
}

string CustomerId
```

**Comment by ShahOdin** [comment]
Thanks @kstich so to sum up, we can use union types in the input position, but smithy's opinionated approach clashes with http requirements for a `GET` endpoint. not allowing me to do use it in a http operation since GET http has undefined behaviour for GET request with a payload and request payload seems to be the only way of passing a unon as input. 

if so, happy for you to close this issue.

**Comment by kstich** [comment]
>Only top-level members of an operation's input, output, and error structures are considered when serializing HTTP messages.

[_HTTP Bindings_](https://awslabs.github.io/smithy/2.0/spec/http-bindings.html#http-bindings)

For a `GET`, you can either use the overload behavior described above or two separate `httpQuery` bound parameters instead of using a `union` or having two separate operations.
