### ISSUE TITLE
Grammar issue | question

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1511]
If my understanding is correct , it seems that the grammar for defining map members requires the new line or comment to appear before any whitespace after the Map Key is defined
as there needs to be a BR before a WS 
Commas are only allowed in the definition of WS not BR
https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-MapMembers

**Comment by mtdowling** [comment]
Ah yeah the BR between map members should probably be 1 or more required WS.
