### ISSUE TITLE
Paginated trait vs specification

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1513]
Hi! My understanding is that, if a service has the `@paginated` trait and none of its operations do, it's as if all the operations got the same `@paginated` trait:

> Attaching the paginated trait to a service provides default pagination configuration settings to all operations bound within the closure of the service. 

However, [the PaginatedTraitValidator class](https://github.com/awslabs/smithy/blob/b653f9c0b2987681b6b00c8607c9bbbd9a0f36e5/smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java) doesn't seem to look at services at all, unless the operation is already annotated with `@paginated`.

Is there some transformation I'm missing (which would copy the trait to all of the service's operations)? Am I misunderstanding the spec? Or is the implementation incorrect?

Example (using [scala-cli](https://scala-cli.virtuslab.org/)):

```scala
//> using lib "software.amazon.smithy:smithy-model:1.26.4"
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.shapes.ShapeId

object a extends App {

  val s =
    """$version: "2"
      |namespace mytest
      |
      |@paginated(inputToken: "test", outputToken: "test")
      |service MyService {
      |  operations: [MyOperation]
      |}
      |
      |operation MyOperation {}""".stripMargin

  println {
    Model
      .assembler()
      .addUnparsedModel("test.smithy", s)
      .assemble()
      .unwrap()
      .expectShape(ShapeId.from("mytest#MyOperation"))
  }
}
```

I thought it would fail because of the missing `test` members in the operation's input and output, but it doesn't. It does break if you move the trait to the operation though.

**Comment by kstich** [comment]
Default pagination configuration from a service is only passed down to operations that are also marked with the `@paginated` trait. If the behavior applied without the operation-level trait, it would be impossible to have default pagination configuration on a service and bind non-paginated operations to it.

We should probably update that line of text to include that the operation must be `@paginated` as well for configuration to apply.

**Comment by kubukoz** [comment]
thanks, I appreciate the clarification!
