### ISSUE TITLE
Grammar issue / questions

### ISSUE THREAD

**Issue by daddykotex** [awslabs/smithy#1522]
I wonder if my understanding is correct. In the [documentation](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ShapeStatement):

ShapeStatements =
    *([ShapeStatement](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ShapeStatement) / [ApplyStatement](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ApplyStatement))

ShapeStatement =
    [TraitStatements](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-TraitStatements) [ShapeBody](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ShapeBody) [BR](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-BR)

Which I understand as: a shape needs to have a BR after their body.

This would mean that a simple document like:

```
$version: "2"
namespace test

structure MyStruct {

}//no new line
```

would not be valid.

 Is my understanding wrong or is the ABNF too strict and what we want is a BR interspersing different shape bodies?

**Comment by mtdowling** [comment]
Yeah, just a BR interspersing different shape bodies is better than requiring a trailing newline (though, I think we _want_ that, but we don't have to require it).

**Comment by daddykotex** [comment]
Another thing that might be an issue with the grammar:

```
@mixin
list MixinList {
    member: String
}

list MixedList with [MixinList] {}
```

In this instance, `MixedList` _does not_ have a member. it comes from the mixin. The grammar says:

ListStatement =
    %s"list" [SP](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-SP) [Identifier](https://smithy.io/2.0/spec/model.html#grammar-token-smithy-Identifier) [[Mixins](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-Mixins)] *[WS](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-WS) [ListMembers](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ListMembers)

ListMembers =
    "{" *[WS](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-WS) [ListMember](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ListMember) *[WS](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-WS) "}"

ListMember =
    [TraitStatements](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-TraitStatements) ([ElidedListMember](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ElidedListMember) / [ExplicitListMember](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ExplicitListMember))
    
I read this as: List needs a ListMembers, and ListMembers needs one of [ElidedListMember](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ElidedListMember) / [ExplicitListMember](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-ExplicitListMember)

**Comment by milesziemer** [comment]
Fixed by https://github.com/awslabs/smithy/pull/1533
