### ISSUE TITLE
Use GitHub releases?

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1532]
Hi! I was wondering if you could look into using github's releases when there's a new Smithy release. This would allow users / tooling authors to easily subscribe to these via the watch feature:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/894884/207142364-d14cee4a-b240-448b-a7cf-e21d37d4d7f0.png">

**Comment by mtdowling** [comment]
We're considering using GitHub releases as part of our effort to start publishing Smithy CLI builds.

**Comment by kstich** [comment]
We've started using GitHub releases in conjunction with publishing the Smithy CLI, [they can be found here](https://github.com/awslabs/smithy/releases).
