### ISSUE TITLE
No protocol tests for `@uniqueItems`

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1541]
The repository used to contain protocol tests for `set` shapes e.g.:

* `RestJsonMalformedSetDuplicateItems`
* `RestJsonMalformedSetNullItem`
* `RestJsonMalformedSetDuplicateBlobs`

In a7a16dfd13426f712934108f46cce3a3bb9d61b4, sets were deprecated in favor of lists with `@uniqueItems`, and the name of these tests changed.

In July, in 1b5737a873033a101066b3d92b9e11d4ed3587c7, the tests were removed cc @gosar:

> For now, removing these tests to unblock smithy 1.22.0 release.

Re-adding the tests would be nice to ensure smithy-rs is compliant (e.g. same validation error message).

As an aside, shouldn't we also add protocol tests for `set` shapes, not only `list` shapes with `@uniqueItems`? While deprecated in IDL v2, users can still use them. In addition, don't we still have to support IDL v1? In which case we need to ensure we return `SerializationException`s if the model was an IDL v1 model, and `ValidationException` in case it was an IDL v2 (?). Alternatively, since in smithy-rs we've never supported `@uniqueItems` or the semantics of `set` shapes:

1. we could abort if we detect a `set` shape in an IDL v1 model when running the server SDK generator, and instruct the user to update their model.
2. we could apply a model transformation to convert `set` shapes to `list` shapes with `@uniqueItems`, and print a warning saying we will be returning `ValidationException`.

Guidance is appreciated on this.

**Comment by mtdowling** [comment]
Yeah, let's add uniqueItems tests.

I don't think we need set tests though. Sets were completely removed in IDL v2. The Rust code generator should treat sets from IDL v1 exactly like a list + uniqueItems, and that's easy to do since a `uniqueItems` trait is added to every IDL v1 set shape automatically (we document that [in the 1.0 spec too](https://smithy.io/1.0/spec/core/model.html#set)).

**Comment by srchase** [comment]
Validation protocol tests for `@uniqueItems` were added in https://github.com/awslabs/smithy/pull/1622.
