### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1548]
Are you opposed to adding multi-line comments and multi-line documentation  perhaps with a star like //* 
I would find it very useful

**Comment by mtdowling** [comment]
I'm hesitant to add more complexity to the grammar, more than one way to make comments, additional ways to define documentation, or the necessary version bump to the IDL to add new syntax. We already support defining documentation via `///` and via `@documentation`. I think IDE plugins for Smithy should be able to easily comment out large sections of models, or make it easier to write out multi-line documentation strings. Also... if I could go back in time, I'd probably have used `#` for documentation comments to make parsing easier... oh well.

If you're in a situation where you really need multi-line documentation that doesn't work well with `///` for whatever reason, you can switch to `@documentation` and use a multi-line string:

```
@documentation("""
    Docs...""")
```

We based the syntactic sugar for documentation around Rust. Rust supports lots of other ways to add docs and comments, and it seems like a recurring debate in the community that there are too many ways to write docs and comments. I'd like to avoid that kind of issue.
