### ISSUE TITLE
Parse inline structures with `for` statement that precedes `with` statement

### ISSUE THREAD

**Issue by srchase** [awslabs/smithy#1558]
The IDL grammar states that [inline operation input/output structures](https://smithy.io/2.0/spec/idl.html#grammar-token-smithy-InlineStructure) can be defined with for-resource statement, followed by a with-mixin statement:
```
InlineStructure =
    ":=" *WS TraitStatements [StructureResource]
          [Mixins] *WS StructureMembers
```

However, when defining a model with the following:
```
operation ListUsersByName {
  input := for User with [UserIds] {}
}
```

A parsing error is thrown:
```
ERROR: - (Model)
     @ /Volumes/workplace/test_model_gradle/model/main.smithy
     |
  17 |   input := for User with [UserIds] {}
     |                     ^
     = Parse error at line 17, column 21 near `with`: Expected: '{', but found 'w'
```

The model can successfully be parsed if the with-mixin and for-resource statements are transposed:
```
operation ListUsersByName {
  input := with [UserIds] for User {}
}
```

**Comment by mtdowling** [comment]
This now works. Tested with 1.33.0
