### ISSUE TITLE
Sensitive structure in logs

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1561]
We generate Debug implementations for logging structures. When a structure is sensitive, should the logs have only the name of the structure (redacting members) or nothing at all?
```
@sensitive
structure Struct { member: String }
```
Logging the structure could be:
* `Struct {}`
* `/* empty */`
* `Struct { member: redacted }`

**Comment by mtdowling** [comment]
I think it should be the last one (`Struct { member: redacted }`). Adding sensitive to a structure is similar to applying sensitive to each member of the shape.

**Comment by 82marbag** [comment]
Thank you, implemented this way
