### ISSUE TITLE
@internal serialization

### ISSUE THREAD

**Issue by daddykotex** [awslabs/smithy#1565]
Recently, I stumbled on https://smithy.io/2.0/spec/type-refinement-traits.html?highlight=internal#default-value-serialization

This is a section related to the `default` trait, but used in conjunction with `@internal`. Then I realized our implementation over at https://github.com/disneystreaming/smithy4s did not deal with `@internal`. So I implemented it.

To me it was clear: `@internal` are not meant to be serialized. But after a round of reviews, other maintainers felt like the documentation only specified that `@internal` should not be serialized if used with `@default`. And I guess we can say that this makes sense, but also it's also kind of counter-intuitive.

So my question is: should a server ever serialize fields annotated with `@internal`?

Ref: https://smithy.io/2.0/spec/documentation-traits.html?highlight=internal#internal-trait https://smithy.io/2.0/spec/type-refinement-traits.html?highlight=internal#default-value-serialization

**Comment by mtdowling** [comment]
Yes, a server should serialize fields annotated with internal (otherwise those members wouldn't be useful for anything other than requests). There are caveats mentioned around whether to serialize defaulted values marked as internal, but those are shoulds not musts.
