### ISSUE TITLE
Streaming on strings

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1568]
Over at https://smithy.io/2.0/spec/streaming.html, I read:

> A data stream is created by applying the [streaming trait](https://smithy.io/2.0/spec/streaming.html#streaming-trait) to a blob or string.

In 13.3:

> Trait selector::
>    :is(blob, union)

Is it possible to apply `@streaming` to strings?

**Comment by mtdowling** [comment]
Ah whoops. No we don't support streaming strings right now and need to correct the docs.
