### ISSUE TITLE
Suggestion:Documentation httpPayload target string enum

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1581]
Perhaps it should be maid clearer that the httpPayload trait can target string enums too 
https://smithy.io/2.0/spec/http-bindings.html#httppayload-trait

**Comment by hpmellema** [comment]
The trait selector in the httpPayload trait documentation specifies that the trait can be applied to string members (`member > :test(string,...)`). String enums are a special case of strings as documented in the base spec (see: https://smithy.io/2.0/spec/model.html#shapes).

Im not sure additional documentation is necessary here as the base spec seems to cover this case. However, if more folks run into this Ill re-open the issue and re-assess.
