### ISSUE TITLE
Streaming in AwsJson1.0 as payload

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1584]
In [13. Streaming](https://smithy.io/2.0/spec/streaming.html):

> If a service supports the [httpPayload trait](https://smithy.io/2.0/spec/http-bindings.html#httppayload-trait), any member that targets a streaming shape must also be marked as @httpPayload.

AwsJson1.0 does not support `@httpPayload`. What is the expected behavior for services that don't support `@httpPayload`, as that trait ensures the targeted member is the unique member in the payload? Does it mean that a streaming member must be the only member of the input/output structure?

Is this valid?
```
@input
structure Example {
    @streaming 
    event: StreamingEvent,
    string: String
}
```

**Comment by mtdowling** [comment]
The `@streaming` trait has its own validation for this. The [docs for the streaming trait](https://smithy.io/2.0/spec/streaming.html#streaming-trait) say:

> The streaming trait is structurally exclusive by target, meaning only a single member of a structure can target a shape marked as streaming.

This is part of the trait definition and automatically validated.

> Does it mean that a streaming member must be the only member of the input/output structure?

No. Other members are the initial-request/initial-response.

**Comment by mtdowling** [comment]
I think this can be closed. Let me know if there's something else to do here.
