### ISSUE TITLE
Annotations collision with documentation

### ISSUE THREAD

**Issue by msosnicki** [awslabs/smithy#1600]
Looks like the order matters when combining annotations and documentation in smithy files. If the annotation goes first, the documentation below it is lost. Is it the desired behavior? Something I missed that is is smithy syntax spec?

I'm using [scala-cli](https://scala-cli.virtuslab.org/) to reproduce the issue. 

```scala
//> using lib "software.amazon.smithy:smithy-model:1.27.2"
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.shapes.ShapeId

import scala.jdk.CollectionConverters.*

val spec =
  """
  |$version: "2"
  |
  |namespace smithy.hello
  |
  |structure Hello {
  |  /// fieldA docs
  |  @required
  |  fieldA: String
  |
  |  @required
  |  /// fieldB docs
  |  fieldB: String
  |
  |  /// fieldC docs
  |  fieldC: String
  |}""".stripMargin

val model = Model.assembler().addUnparsedModel("spec.smithy", spec).assemble().unwrap()

model.getShape(ShapeId.from("smithy.hello#Hello")).get().members().asScala.foreach { member =>
  println(s"Member: ${member
      .getMemberName()} Traits: ${member.getAllTraits().values.asScala.map(t => t.toShapeId()).mkString("[", ",", "]")}")
}
```

The above, prints:
```
Member: fieldA Traits: [smithy.api#documentation,smithy.api#required]
Member: fieldB Traits: [smithy.api#required]
Member: fieldC Traits: [smithy.api#documentation]
```

I think the same problem applies for other kinds of annotations. Not reproduced here, but this corresponds to what I saw when initially spotting this problem.

**Comment by kstich** [comment]
This is because documentation comments must appear before traits applied to a member. This is the case for both `fieldA` (before `@required`) and `fieldC` (no traits,) but not `fieldB`.

>Documentation comments are only treated as shape documentation when the comment appears immediately before a shape, and documentation comments MUST appear before any [traits](https://smithy.io/2.0/spec/model.html#traits) applied to the shape in order for the documentation to be applied to a shape.

[See _Placement_ in the Documentation comment documentation](https://smithy.io/2.0/spec/idl.html#documentation-comment).
