### ISSUE TITLE
Expected behavior for empty lists with @httpQuery trait 

### ISSUE THREAD

**Issue by xytxxx** [awslabs/smithy#1608]
Hi team, 
What the expected behavior is for marshalling an empty list in the AWS JSON protocols? I am trying to pass an empty array through http query but it gets marshalled to null (no http query is sent) by the Java Client.
Here is field that I am trying to send empty array with:
```
  @httpQuery("personId")
  personIds: IdList
```
And here is my API gateway integration:
```
uri: "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/{{{SendRequisitionToApproversLambda_Arn}}}/invocations",
httpMethod: "POST",
passThroughBehavior: "when_no_match",
type: "aws",
requestTemplates: {"application/json" :
    "#set ($root=$input.path('$'))
    {
     ......
      #if($method.request.multivaluequerystring.get('personId').size() > 0)
      \"personIds\": [
        #foreach($id in $method.request.multivaluequerystring.get('personId'))
        #if($id.length()!=0)\"$id\"#if($foreach.hasNext), #end#end
        #end
      ],#end
      ...
    }",
```

**Comment by srchase** [comment]
See the tests added in https://github.com/awslabs/smithy/pull/1629

> When serializing an empty string for param Foo, Foo= is serialized in the query string. An empty list for param Foo cannot also be serialized as Foo= as one might expect. Instead, it is omitted to clearly differentiate between an empty string, and an empty list.
