### ISSUE TITLE
RestJson1 protocol test Question

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1633]
In a couple of places the empty json object is used in the Params field
My understanding of serialization is this should be deserialized to an empty object of that type i.e. if its a Map - the empty Map etc..
However for the protocol test to pass this would require the instantiation of an empty Map automatically on an optional parameter.
An example would be this test https://github.com/awslabs/smithy/blob/8f32289b8f23bd53b1676af34f703680a79c6daa/smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy#L55

**Comment by srchase** [comment]
Thanks for raising this issue.

This should be a client-only test.

Clients should omit the empty map when serializing the request. Servers however should not instantiate an optional parameter when it is not set as a header.

I'll get a PR up to fix this.
