### ISSUE TITLE
How to build multiple smithy files

### ISSUE THREAD

**Issue by ericxinzhang** [awslabs/smithy#1650]
I've got a repository with multiple .smithy files, and I've configured `openapi` plugin to generate OpenAPI specs.

In `smithy-build.json` file, given the following syntax, it seems to me that `openapi` plugin supports only one service at a time.

```
{
  "version": "2.0",
  "plugins": {
    "openapi": {
      "service": "com.example#Service1",
      "protocol": "aws.protocols#restJson1"
    }
  }
}
```

My question is, how can the build task builds multiple smithy files and generate multiple OpenAPI specs (Service1.openapi.json, Service2.openapi.json, etc)? 

I tried running the build task multiple times and manually updating the `smithy-build.json` file in between, it all worked fine. I just don't know how to let the build task do all these for me. 

I am not familiar with gradle. Any advice is appreciated.

**Comment by JordonPhillips** [comment]
This is a use case for projections: https://smithy.io/2.0/guides/building-models/build-config.html#projections

essentially you'll have one projection per service with the openapi plugin being configured seperately in each projection, like so:

```
{
    "version": "2.0",
    "projections": {
        "service1": {
            "plugins": {
                "openapi": {
                    "service": "com.example#Service1",
                    "protocol": "aws.protocols#restJson1"
                }
            }
        },
        "service2": {
            "plugins": {
                "openapi": {
                    "service": "com.example#Service2",
                    "protocol": "aws.protocols#restJson1"
                }
            }
        }
    }
}
```

**Comment by ericxinzhang** [comment]
Thank you so much Jordon. I should have read the projection section more carefully.
