### ISSUE TITLE
modeling a JSON output with nested arrays of differently shaped objects

### ISSUE THREAD

**Issue by joelvanderhoof** [awslabs/smithy#1655]
I've run into what seems to be a roadblock while writing a `structure` for a HTTP operation output. The output is a large JSON object with multiple nested arrays of differently shaped objects. There is a set number of variations for these objects in the arrays. Using a `structure` with `list` members works up to a point. However, I'm not able to model the different object shapes within the array since `list` only allows a single homogeneous `member`. Is there a way to properly model this in Smithy?

For example: 
```{
data: {
    "columnRows": [
      {
        "fieldType": "foo"
        "requiredMetadata": {}
      },
      {
        "type":  "spacer"
        "width": 5
      },
      {
        "fieldType": "bar",
        "options": []
      },
    ]
  }
}

**Comment by kstich** [comment]
[A `union` shape the recommended way to handle this kind of variance](https://smithy.io/2.0/spec/aggregate-types.html#union), a set of different but fixed types.

```
structure FooRequest {
    data: Data
}

structure Data {
    columnRows: ColumnList
}

list ColumnList {
    member: ColumnEntry
}

union ColumnEntry {
    foo: Foo
    spacer: Spacer
    bar: Bar
}

structure Foo {
    requiredMetadata: RequiredMetadata
}

structure Spacer {
    width: Integer
}

structure Bar {
    options: OptionsList
}
```

However, this would change the wire output with a layer of indirection - hoisting `type` up as the tag of the union. If maintaining compatibility with this wire format is key, [a `document` type represents protocol-agnostic open content](https://smithy.io/2.0/spec/simple-types.html#document) that can vary in the way described. Consumers of the API would need to know how to marshal values from the document into the required types.
