### ISSUE TITLE
Smithy to GRPC

### ISSUE THREAD

**Issue by obaidsalikeen** [awslabs/smithy#1668]
Is it possible to generate GRPC from Smithy service definitions? 

I have the following case: 
I have an object (service contract) defined in Smithy. I want to used that object in my GRPC/proto application.

So, what will you recommend, and why?
1. Should I convert Smithy to proto definitions and then import those proto files in my service? this is easy but it needs a translation step each time you update the version of the proto files.
2. Should I move completely to Smithy? Can Smithy generate GRPC code? if it can, I could simply move service definitions in Smithy and then generate GRPC code, my service will be happy.

Thanks

**Comment by kubukoz** [comment]
Hey, you may want to take a look at https://github.com/disneystreaming/alloy/#alloyprotogrpc :)

**Comment by yisraelU** [comment]
Also https://github.com/disneystreaming/smithy-translate#protobuf

**Comment by mtdowling** [comment]
Looks like you have some good options there, so I'll go ahead and close this.
