### ISSUE TITLE
Does smithy generates the swagger definitions based on the AWS SDK

### ISSUE THREAD

**Issue by bagajjal** [awslabs/smithy#1704]
AWS SDK for various resource types are defined at https://github.com/aws/aws-sdk-net/tree/master/generator/ServiceModels.
Is it possible to take this as a source and produce swagger definitions?

Looking at the https://github.com/aws/aws-sdk-net/issues/1619 issue, the SDKs are generated based on the smithy tool.

**Comment by hpmellema** [comment]
Yes, Smithy can be used to generate OpenAPI (Swagger) specs. You can find a guide on Smithy to OpenAPI conversion here: https://smithy.io/2.0/guides/converting-to-openapi.html

**Comment by mtdowling** [comment]
No, we don’t produce OpenAPI models for AWS because the format is too different from Smithy, the model we use to describe services. See also https://github.com/awslabs/smithy/issues/1701#issuecomment-1499106125
