### ISSUE TITLE
How to resolve error "no repositories are defined"?

### ISSUE THREAD

**Issue by ikanni** [awslabs/smithy#1720]
- We are trying out the steps mentioned in https://smithy.io/2.0/guides/converting-to-openapi.html#converting-to-openapi-with-smithy-build 
- gradle build failed with below error 
1.   Cannot resolve external dependency software.amazon.smithy:smithy-aws-traits:1.29.0 because no repositories are defined.
2. Cannot resolve external dependency software.amazon.smithy:smithy-cli:1.29.0 because no repositories are defined.
- **How to resolve error "no repositories are defined"?**
- Setting the SMITHY_MAVEN_REPOS like the below did not solve the problem
SMITHY_MAVEN_REPOS='https://repo.maven.apache.org/maven2|https://central.sonatype.com/'

### gradle build output screen:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/16600949/229978037-904e8299-d1d4-45b9-b2e9-77b0682cefbe.png">

**Comment by mtdowling** [comment]
The Gradle plug-in uses Gradle resolvers and doesn’t rely on the CLI for dependency resolution, so you’ll need to define repositories in your build.gradle file. Here’s an example: https://github.com/awslabs/smithy-gradle-plugin/tree/23b97381b5ca18b237312c27ce44a13b15e9644c/examples/source-projection

**Comment by ikanni** [comment]
Thank you, Michael! I will give a try and update.

**Comment by ikanni** [comment]
Thank you! Closing this issue. I was able to generate OpenAPi for Service Foo with below 3 files

<img width="365" alt="image" src="https://user-images.githubusercontent.com/16600949/230101108-dbaf9168-39f6-4b34-a402-70111b63bef8.png">

<img width="608" alt="image" src="https://user-images.githubusercontent.com/16600949/230101527-be42bf4c-9827-4422-ad83-dd193a5a81ec.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/16600949/230101623-dda27d1a-b0bb-49c9-986c-62117dc16ddc.png">
