### ISSUE TITLE
Is it possible to generate the Swagger definitions using awslabs/smithy-rs/tree/main/aws/sdk/aws-models ?

### ISSUE THREAD

**Issue by ikanni** [awslabs/smithy#1722]
We understand **Smithy** [code generators for Rust](https://github.com/awslabs/smithy-rs) is used to generate the entire [aws-sdk-rust/next](https://github.com/awslabs/aws-sdk-rust/tree/next).

It looks like smithy-rs repo uses the [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models) to generate aws-sdk-rust.

Is it possible to generate the Swagger definitions (openapi) using the same aws-models (used to generate the rust SDK)? If yes, could you please guide us with the required steps.

**Comment by mtdowling** [comment]
No, not all AWS services use a protocol that works with OpenAPI. You could generate anything that uses rest-json1, but other protocols are unsupported.

**Comment by ikanni** [comment]
Thank you, Michael!

Few follow-up questions:
1. Are these [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models) used to generate [aws-sdk-rust/next](https://github.com/awslabs/aws-sdk-rust/tree/next)?
2. We could not find rest-json1 trait in [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models). Does it mean we cannot generate the swagger definitions based on the files in  [aws-models](https://github.com/awslabs/smithy-rs/tree/main/aws/sdk/aws-models).
3. **Is there a good source which has the rest-json1 trait for all the aws services?**

**Comment by mtdowling** [comment]
1. Those models look like a small subset of all models. You can find all models used to build the AWS SDK for Rust at https://github.com/awslabs/aws-sdk-rust/tree/main/aws-models.
2. Sorry it's `restJson1`. See https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html.
3. Since it's a flat directory structure, you could just grep the files for `restJson1`.

**Comment by ikanni** [comment]
Thank you! If I understand correctly, we need to grep for '@restJson1'

**Comment by mtdowling** [comment]
Just restJson1 since these are JSON models.

**Comment by ikanni** [comment]
Yes, most of the models has the restJson1 like the below
<img width="726" alt="image" src="https://user-images.githubusercontent.com/16600949/230247952-c7cc1372-961e-44cf-8192-8b05a6247580.png">

Do you have any specific steps to follow to generate the Swagger definitions (openapi) for the above models with restJson1 ?

**Comment by mtdowling** [comment]
Sure, this doc provides a guide covering how to convert a model to OpenAPI:  https://smithy.io/2.0/guides/converting-to-openapi.html. There’s no built in functionally to do any kind of bulk conversion.

What are you wanting to do with the generated OpenAPI definitions?
