### ISSUE TITLE
Guidance : httpPrefixHeaders

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1771]
When a Map String -≥ String , is targeted by this trait , implementations are meant to extract all headers , prefix them with the prefix and place them in the map
This seems to be the only trait that grabs all headers in an untargeted fashion.
That said , are there certain headers that SHOULD NOT be placed into the Map ?
From this test , it would seem that the Content-Type header should not be extracted https://github.com/awslabs/smithy/blob/3675c72baffd4565417a96ca1700c0d32fe1f5bb/smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy#L108

**Comment by JordonPhillips** [comment]
No, you're meant to grab all headers. The `headers` field in the request tests doesn't preclude other headers existing. That test you linked is therefore valid, just incomplete.

**Comment by yisraelU** [comment]
this is a response test 
the client is meant to deserialize the HTTP response to an object, that object should equal the one modeled in the params

**Comment by JordonPhillips** [comment]
Right, but when you construct the http response to give to a client under test you would only populate those headers that are present. In a real world scenario there may be other things there, but not in the test.
