### ISSUE TITLE
Constraint traits and backwards compatibility

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#1775]
Should the [Evolving Models](https://smithy.io/2.0/guides/evolving-models.html) page include provisions about how [constraint traits](https://smithy.io/2.0/spec/constraint-traits.html) affect the evolvability of a model? After all, it has provisions about `@required`, which has similar effects to those of constraint traits.

For example, I would consider adding a constraint trait that further restricts the set of values an input shape can take to be backwards incompatible: an operation could start rejecting requests that previously were accepted.

Adding a constraint trait to a shape that lies in an operation's output closure should also come with a word of caution: that operation would not be able to return previously stored data that only adhered to the relaxed schema.

**Comment by sugmanue** [comment]
Good idea. I have added a note [here](https://github.com/awslabs/smithy/pull/1826). Notice that this list is not extensive but I think that adding a small note to cover constraint traits it's worth it.

**Comment by sugmanue** [comment]
The PR has been merged and it should be visible after the next release.
