### ISSUE TITLE
Unable to run ./mill smithy.publishLocal on Windows : java.lang.IllegalArgumentException: Illegal character in opaque part at index 2

### ISSUE THREAD

**Issue by vbuddharaju** [awslabs/smithy#1796]
I tried publishing the smithy model locally using the command "./mill smithy.publishLocal", using Windows version & WSL / MSYS2 / Cycgin / Git-Bash version of mill from http://mill-build.com/mill/Installation_IDE_Support.html#_manual.

**Comment by mtdowling** [comment]
It looks like this is thrown by SxmSourceLocationTransformer.java? I don't know what that code looks like, but that would be something written outside of this repository.
