### ISSUE TITLE
Broken link in installation docs

### ISSUE THREAD

**Issue by akhilesharora** [awslabs/smithy#1811]
The link for smithy-cli [installation]( https://smithy.io/2.0/guides/smithy-cli/cli_installation.html?highlight=installation) is broken!

The latest release at the moment is [https://github.com/awslabs/smithy/releases/tag/1.31.0](https://github.com/awslabs/smithy/releases) while the doc instructs to ```mkdir -p smithy-install/smithy && \
    curl -L https://github.com/awslabs/smithy/releases/download/1.32.0/smithy-cli-linux-x86_64.tar.gz -o smithy-install/smithy-cli-linux-x86_64.tar.gz && \
    tar xvzf smithy-install/smithy-cli-linux-x86_64.tar.gz -C smithy-install/smithy```

The release assets are missing in the latest tag [v1.32](https://github.com/awslabs/smithy/releases/tag/1.32.0) and maybe a possible solution could be always fetch the latest release rather than tags.

**Comment by haydenbaker** [comment]
Thank you for creating an issue. We are currently releasing that version. It should be fixed now.
