### ISSUE TITLE
[awsJson1_x] Content-Encoding tests inconsistent with specification

### ISSUE THREAD

**Issue by Baccata** [awslabs/smithy#1827]
Hi everyone. My team has noticed that there are tests around compression for the `awsJson1_0` and `awsJson1_1` protocols that are inconsistent with the specification. 

These tests exercise gzip encoding in the context when the user has the possibility of providing a [custom encoding](https://github.com/awslabs/smithy/blob/8c8accbe2b0dfe59a47c7d440d41f89324d97328/smithy-aws-protocol-tests/model/awsJson1_0/requestCompression.smithy#L305-L311
) via a member of the structure input annotated with `@httpHeader("Content-Encoding)`. 

However, the corresponding protocol specification makes it quite clear that http-binding traits [must be ignored](https://smithy.io/2.0/aws/protocols/aws-json-1_0-protocol.html#protocol-behaviors)

Can you elaborate on whether the specification or the test is correct ?

**Comment by syall** [comment]
Hi @Baccata, thanks for catching this issue! The protocol tests are invalid due to the reasons you mentioned, and a PR has been put up to fix them.

**Comment by syall** [comment]
Hi @Baccata , #1831 has been merged, so the protocol test fixes will be available in the next smithy release.
