### ISSUE TITLE
CLI: ignore non-Smithy-model JSON files?

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1841]
Hi!

I'm trying to use the CLI, and I've also [faced this problem before](https://github.com/kubukoz/smithy-playground/pull/290) using plain smithy-model. Perhaps there's something we can do in smithy itself to assist this usecase:

In my org's repo, I've seen some people put non-Smithy files (e.g. JSON body examples for a given endpoint) into the same directory as their Smithy specs. It probably makes sense to keep these close to the specs, rather than in a separate directory structure.

However, these make almost all the tooling fail validation: e.g. this file

```json
{
  "foo": "bar"
}
```

would fail because:

```
Missing expected member smithy.
```

For other files (non-JSON), it seems like the loader is ignoring them and just emitting a warning. Could we do the same for JSON files, if they _don't_ have that `smithy` member?

This could be an opt-in flag too, although for optimal UX I would suggest making it the default.

**Comment by mtdowling** [comment]
While I think Smithy models should be in dedicated directories separate from non-Smithy models, and the given example file should be covered by the Smithy `@examples` trait, I think this feature request makes sense.

**Comment by kubukoz** [comment]
> While I think Smithy models should be in dedicated directories separate from non-Smithy models, and the given example file should be covered by the Smithy `@examples` trait, I think this feature request makes sense.

randomly stumbled upon this after all this time, and I think one of the reasons to _not_ just use `@examples` is that raw JSON files can be passed to non-smithy tools more easily than metadata (e.g. curl is one such tool) - so I think the way you went with was a good call :+1:
