### ISSUE TITLE
How to generate clients for AWS services

### ISSUE THREAD

**Issue by andre2007** [awslabs/smithy#190]
I am not sure whether my understanding of smithy is correct.
Can it be used to generate clients for e.g. S3 / SQS for a programming language like D?
Where are the s3 / sqs smithy model files located?

How are the aws-crt-* libraries related to smithy? Are they the base for generating the clients / servers?

**Comment by JordonPhillips** [comment]
Yep, Smithy will absolutely be able to be used to generate clients for AWS services in any programming language. We haven't published the Smithy models for the services yet, but we plan to in the future.

The CRT libraries absolutely can be used as a base for generating clients and servers, though I would ask on their repos about specific capabilities.

**Comment by mtdowling** [comment]
Let's track this in #102 since they are very similar issues.
