### ISSUE TITLE
Deprecate then remove ShapeIndex

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy#208]
ShapeIndex is an abstraction that basically is a map of ShapeId to Shape. A Model contains a ShapeIndex, metadata, and a version. A ShapeIndex as a separate abstraction from Model makes code harder to write and adds no value in its separation. I propose we release a backward compatible change that first adds the ShapeIndex API into Model and deprecates any ShapeIndex based API. Then, in the next major version (i.e., 0.10.0), we will remove ShapeIndex and the deprecated APIs. This will take probably several days of super lame find, replace, and edit changes, but I think it's a win for API clarity.

- [x] Deprecate ShapeIndex in 0.9.x
- [x] Remove ShapeIndex in 0.10.x

**Comment by trivikr** [comment]
Can this be resolved?
Refs: #209

**Comment by kstich** [comment]
No, it also tracks the removal in a future version.
