### ISSUE TITLE
[0.9.x] Create a "rename" model transformer

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy#288]
There are use cases where you need to rename a shape to a new name (refactoring, transforming to a new namespace, automatically de-conflict shape names). We should add a model transformer that handles this for you. This kind of transformation would ideally support things like renaming namespaces, renaming names, renaming members, and then updating all references to the renamed shapes (even idRef references). This should ideally be handled in a single pass so that an excessive number intemediate models aren't created. It would be great if the transformation could throw when a collision occurs and state the original shape IDs of the colliding shapes (perhaps with a way to allow the collision using a flag or something).

**Comment by msharshath** [comment]
Hello,

I need the model that rename my words to other words using transformer.
i can see in the comment you built that model.
Can i know where can i find that
