### ISSUE TITLE
Batch operation implicit identifier example

### ISSUE THREAD

**Issue by benkehoe** [awslabs/smithy#295]
In [core.rst](https://github.com/awslabs/smithy/blob/master/docs/source/spec/core.rst), there is the following example:
```smithy
resource Forecast {
    identifiers: {
        forecastId: ForecastId,
    },
    operations: [BatchPutForecasts],
}

operation BatchPutForecasts {
    input: BatchPutForecastsInput,
    output: BatchPutForecastsOutput
}

structure BatchPutForecastsInput {
    @required
    forecasts: BatchPutForecastList,
}
```
with the following text:
> `BatchPutForecasts` forms a valid collection operation with implicit identifier bindings because `BatchPutForecastsInput` does not require an input member named "forecastId" that targets `ForecastId`.

Given that `BatchPutForecasts` is a collection operation, doesn't that mean `Forecast` should look like this?
```smithy
resource Forecast {
    identifiers: {
        forecastId: ForecastId,
    },
    collectionOperations: [BatchPutForecasts],
}
```

**Comment by JordonPhillips** [comment]
Nice catch! You are absolutely correct, that would actually fail validation. We should probably have something to automatically enforce all documentation examples pass smithy validation.
