### ISSUE TITLE
Union Shape type should be "union" in documentation

### ISSUE THREAD

**Issue by trivikr** [awslabs/smithy#447]
**Describe the bug**
Union Shape type is "structure" in documentation

**To Reproduce**
Visit https://awslabs.github.io/smithy/1.0/spec/core/shapes.html?highlight=union#union

**Expected behavior**
Union Shape type should be "union" in documentation

**Screenshots**

<details>
<summary>Screenshot</summary>

![Screen Shot 2020-05-27 at 9 19 15 AM](https://user-images.githubusercontent.com/16024985/83046011-39969900-9ffb-11ea-9190-05e90b888a13.png)

</details>

**Comment by JordonPhillips** [comment]
Fixed with #449
