### ISSUE TITLE
smithy-build.json without required field does not fail as expected

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy#448]
Steps to reproduce:
1. Notice that `output` is defined as a required field in `smithy-build.json` in https://awslabs.github.io/smithy/guides/building-models/build-config.html
2. Follow README example which does not define `output`.

Expected results: The lack of required field should produce an error
Actual results: Provided a model, the build completes successfully

**Comment by mtdowling** [comment]
Ah, this is erroneous documentation -- output isn't required any longer. We'll fix.

**Comment by JordonPhillips** [comment]
Fixed with #449
