### ISSUE TITLE
Following quickstart guide leads to a broken build

### ISSUE THREAD

**Issue by ConnorKirk** [awslabs/smithy#460]
Hi! 
To learn Smithy, I am following the [quickstart guide](https://awslabs.github.io/smithy/quickstart.html).

At [Build the Model](https://awslabs.github.io/smithy/quickstart.html#building-the-model), the build will fail for those who have followed the guide linearly.

This is because the `GetForecast` operation is not defined. 
Adding the `GetForecast` operation, input and output to the model fixes this. However these shapes are only present in the final sample provided at the end of the guide. 

This may be confusing to users attempting to learn Smithy.
Could I suggest updating the guide to include the code for the `GetForecast` operation before instructing the user to build the model.

Connor

**Comment by ConnorKirk** [comment]
To add to this, I am happy to contribute a PR to update the quickstart to fix this problem

**Comment by srchase** [comment]
@ConnorKirk,

We'd be happy to take a PR if you want to open one.

Thanks for opening this issue!
