### ISSUE TITLE
Clarify httpLabel timestamp serialization rules

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy#521]
Suggestion for a clarification in the spec:

Serialization rules for [httpLabel](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httplabel-trait) says:
> timestamp values are serialized as an RFC 3339 string (e.g., 1990-12-31T23:59:60Z).

Yet we have a test with different formats for labels with timestamp shapes: https://github.com/awslabs/smithy/blob/master/smithy-aws-protocol-tests/model/restJson1/http-labels.smithy#L88

Perhaps it should have an additional clarification because I initially took that as "timestamps are always serialized as RFC3339 when bound to a label"

**Comment by kstich** [comment]
The update here needs an update [in the docs for `@httpHeader` as well](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpheader-trait), it makes similar serialization comments for IMF-fixdate.
