### ISSUE TITLE
HttpResponseCode protocol test does not specify the correct http response via http trait

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy#625]
In implementing codegen for `HttpResponseCode` test, I am unable to get the test to pass, because the Http trait is specifying (via default) a 200 return, where the test expections model a value of 201.  

Expected behavior: the `http` trait in the test specifes 201 as the expected response code.

**Comment by JordonPhillips** [comment]
This is intended behavior. The `HttpResponseCode` trait is used in cases where there can be multiple response codes. Lambda, for example, can return a 200 or 201 on some of its operations.
