### ISSUE TITLE
Build instructions for smithy

### ISSUE THREAD

**Issue by Johnlon** [awslabs/smithy#699]
How do I build smithy from source?
Seems not to build on clean "./gradlew build" nor "docker build ."

Any reliable instructions on building main branch?

**Comment by kstich** [comment]
Can you provide any more information on what error you're receiving when you try to build? Running `./gradlew build` should be all you need.

**Comment by Johnlon** [comment]
Hi I simply checked out main and ran the build and it failed.

I retried with the gradle 6 branch and it worked.

I will try and run main again tomorrow or Thurs.

**Comment by mtdowling** [comment]
Hey @Johnlon -- were you able to get it working? Is there anything else we can help you with on this issue? We'll go ahead and close this issue in a week or so if we don't hear back.
