### ISSUE TITLE
language support roadmap?

### ISSUE THREAD

**Issue by aaylward** [awslabs/smithy#733]
Hi Smithy folks,

Is there a roadmap I can look at or an email list I can subscribe to for updates about language specific tooling? For example, how can I generate a smithy service in some non-java language?

Thanks very much!

**Comment by mtdowling** [comment]
Are you asking for more language targets of Smithy code generation (like building clients or servers for more languages), or more implementations of Smithy models and build tooling in other languages (like a version of what you see in this project, just written in another language)?

**Comment by aaylward** [comment]
Thanks for clarifying -- I'm asking for more language targets so I can write my smithy service in language X and generate clients in languages X, Y, and Z. I'm interested in java, python, c++, and typescript ( I'm pumped to see https://github.com/awslabs/smithy-typescript ). Thanks again!
