### ISSUE TITLE
smithy-aws-cloudformation-traits does not set additionalProperties: false on all object types

### ISSUE THREAD

**Issue by workeitel** [awslabs/smithy#750]
CloudFormation requires additionalProperties to be false https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/49

Smithy already applies additionalProperties to the top-level: https://github.com/awslabs/smithy/blob/main/smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/CfnConverter.java#L127-L129 

But it needs to be added to every object. Expected output:

```
"Context": {
    "additionalProperties": false,
    "type": "object",
   ...
```

**Comment by kstich** [comment]
Thanks for the report. We'll add an internal `JsonSchemaMapper` that sets this property by default.
