### ISSUE TITLE
smithy-aws-cloudformation-traits does not mark top-level properties as required

### ISSUE THREAD

**Issue by workeitel** [awslabs/smithy#751]
The CloudFormation Resource type schema https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html allows to define properties required. Smithy currently does not mark top-level non-optional properties in the `required` section:

```
{
   ...
    "properties": {
         "propertyName": {
            "description": "string",
            "type": "string",
             . . . 
        },
 
        },
    },
    "required": [   // not added in Smithy
        "propertyName"
    ],
   ...
```

**Comment by kstich** [comment]
Looks like we'll need to add support for determining this field and [the new `conditionalCreateOnlyProperties` field](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/121).

For now, you can set these properties directly with [the `jsonAdd` configuration setting](https://awslabs.github.io/smithy/1.0/guides/generating-cloudformation-resources.html#generate-cloudformation-setting-jsonadd):

```
"jsonAdd": {
    "smithy.example#Queue": {
        "/required": [
            "propertyName"
        ]
    }
}
```
