### ISSUE TITLE
Mismatch between structure and test Xml node names in restXml protocol test

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy#756]
In the `restXml` protocol test suite, `IgnoreQueryParamsInResponse` specifies [this Xml](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restXml/http-query.smithy#L279) to be deserialized, however [references a structure](https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restXml/http-query.smithy#L267) with a slightly different name.  This results in a test error (not failure) because the expected top-level xml node does not match what the deserializer is expecting.

**Comment by kstich** [comment]
Fix merged in #757
