### ISSUE TITLE
Smithy fails to build on OSX

### ISSUE THREAD

**Issue by aknuds1** [awslabs/smithy#763]
Hello

I'm trying to build Smithy on OSX 11.2.3, but it fails with the following error:

```
/Users/arve/Projects/grafana/smithy/smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java:481: error: unexpected heading used: <H2>, compared to implicit preceding heading: <H3>
     * <h2>Implementation notes</h2>
```

I'm actually unsure which Java SDK is being used on this machine, since I'm not a Java developer, and javac is installed under /usr/bin/ while I thought it would be installed by Homebrew instead. 

```
$ which javac
/usr/bin/javac
$ javac -version
javac 1.8.0_282
```

Changing `h2` to `h4` on the line in question fixes the issue.

**Comment by srchase** [comment]
Are you able to build this branch successfully? [disable-html-checking](https://github.com/awslabs/smithy/tree/disable-html-checking)

This looks like an issue that impacts later versions of the SDK, not the Java 8 version that your `javac --version` is reporting.

**Comment by aknuds1** [comment]
> Are you able to build this branch successfully? [disable-html-checking](https://github.com/awslabs/smithy/tree/disable-html-checking)

@srchase sadly that fails in the same way as master does.
 
> This looks like an issue that impacts later versions of Java, not the Java 8 version that your `javac --version` is reporting.

I'm a doofus when it comes to Java, haven't touched it in 6 years, is it possible that another JDK than that of /usr/bin/javac is used?

**Comment by srchase** [comment]
I switched to JDK15 and was able to reproduce this issue.

I would check what `JAVA_HOME` is set to.  It may be pointing to different version of Java, which is what Gradle is picking up to perform the build.

**Comment by aknuds1** [comment]
@srchase `$JAVA_HOME` is unset for me.
