### ISSUE TITLE
hostPrefix property in endpoint trait should validate prefix ends in dot (.)

### ISSUE THREAD

**Issue by mullermp** [awslabs/smithy#778]
The endpoint trait is not required to end in a dot. Is this by design? In the Smithy docs for `hostLabel` it has this example:

```
@endpoint(hostPrefix: "{foo}.data")
```

But for an endpoint `example.com` and `foo = "foo"` it would become `foo.dataexample.com`, unless clients or code generators are validating against this. I think it's dangerous to allow this because it changes the configured host and not limited to prefixing as the trait suggests. If you agree, I think it also makes sense to call out this validation in the documentation, too.

**Comment by JordonPhillips** [comment]
> I think it's dangerous to allow this because it changes the configured host

The whole point of this trait is to allow changing the host, so I don't see why we would forbid this behavior. (We couldn't even if we wanted to since 3/8 of the AWS services that use this don't end it in a period.) Still, we should probably attach an info or warning validation to point out the issue for non-aws services that could potentially be changing their second level domain.

**Comment by mullermp** [comment]
>The whole point of this trait is to allow changing the host

I would think that a trait called "hostPrefix" would only prefix the host, not change to an entirely different TLD if misconfigured.. What AWS services have prefixes that don't end in a period?

**Comment by JordonPhillips** [comment]
Well you'd never be able to change the TLD unless the SDK let you pass in an invalid endpoint to start. You *can* change the 2LD. That's probably a really bad idea if there's a host label in there, which is why the validation I added targets that.

> What AWS services have prefixes that don't end in a period?

chime, sfn, and servicediscovery

**Comment by mullermp** [comment]
Thanks
