### ISSUE TITLE
Constraint trait for member value relationships/effects

### ISSUE THREAD

**Issue by vcschapp** [awslabs/smithy#787]
My team is using Smithy extensively for API modelling and getting some great results!

One gap we are finding is in the [constraint traits](https://awslabs.github.io/smithy/1.0/spec/core/constraint-traits.html#uniqueitems-trait). The ones that exist are pretty great, however they are not capturing some repetitive use cases we have. One such use case is:

- **Field value implications.** This is a slightly more complex use case than [mutually exclusive members](https://github.com/awslabs/smithy/issues/786). The desired behavior is that the *value* set on a structure member has implications for constraints being applied to other fields. Essentially, setting field `Foo` to value `X` is incompatible with some other value for a field `Bar`. You can imagine here that the constraints on `Foo` could be range constraints as well as discrete value constraints.

My team owns our own code generator for our server side code, so we translate the Smithy model into code ourselves. If these constraints are implemented into the language, we can take it from there by updating our code generator to auto-generate the code from the constraints that we're currently writing by hand.

# Example

```
// The @impliedConstraints annotation contains an array of objects where each
// object has a value matching field ("value", "range", "length", "pattern" that
// specifies what values of the member cause the effects; and a "constraints" field
// which specifies what constraints the matching value implies onto other members
// of the structure.
structure S {
    // When the field Foo is set to a value in the range 10-20, the field Bar may not
    // be set, and the field Baz becomes @required.
    @impliedConstraints(
       [
           {
               "range": [10, 20],
               "constraints": [
                   {
                       "members": ["Bar"],
                       "excluded": true
                   },
                   {
                       "members": "[Baz"],
                       "required": true
                   }
               ]
           }
       ]
    )
    Foo: MyInteger,

    // When the field Bar is set to the value "Gorgonzola", the field "Ham" must
    // match the regular expression /Proscuitto|Panchetta/.
    @impliedConstraints(
        [
            "value": ["Gorgonzola"],
            "constraints": [
                {
                    "members": ["Ham"],
                    "pattern": "Proscuitto|Panchetta"
                }
            ]
        ]
    )
    Bar: MyString,

    Baz: MyString,

    Ham: MyString,
}
```

**Comment by mtdowling** [comment]
It's an interesting idea, but I'd be worried about how much complexity this would add for people to be able to easily understand models, code generation, and documentation of services. There are other implications here too that would significantly complicate Smithy's meta-model (like traits defined within traits).

**Comment by mtdowling** [comment]
Given the complexity that would come with this (in readability, modeling, and implementation), I don't see it as something we can support in Smithy's built-in traits. However, anyone can create custom traits and extend Smithy code generators to experiment with features like this.
