### ISSUE TITLE
Null Pointer Exception in cli with smithy-build.json argument and non-empty imports

### ISSUE THREAD

**Issue by jonhoo** [awslabs/smithy#811]
To reproduce, first create a `smithy-build.json` with the contents
```json
{
  "version": "1.0",
  "projections": {
    "example": {
      "imports": ["/dev/null"]
    }
  }
}
```
The path can be anything — it doesn't have to exist.

Then, invoke the smithy CLI with:
```console
$ java software.amazon.smithy.cli.SmithyCli build smithy-build.json
Building Smithy model sources: [smithy-build.json]
Loading Smithy configs: [smithy-build.json]
null
```

The `null` gets printed by
https://github.com/awslabs/smithy/blob/6cf0fe4fae5a2b2d7f3f58a34222d957b5b78612/smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java#L150
after a null pointer exception is raised when trying to access the configuration file here
https://github.com/awslabs/smithy/blob/6cf0fe4fae5a2b2d7f3f58a34222d957b5b78612/smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java#L94
That, in turn, arises because `baseImportPath` is `null` here
https://github.com/awslabs/smithy/blob/6cf0fe4fae5a2b2d7f3f58a34222d957b5b78612/smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java#L79
because `path` (which is `smithy-build.json`) has no parent here
https://github.com/awslabs/smithy/blob/6cf0fe4fae5a2b2d7f3f58a34222d957b5b78612/smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java#L47

Ultimately, the right fix here is probably to set `baseImportPath` to `.` if `path.getParent()` is `null`.

It might also be nice to update `printException` to print something more meaningful than just `null` when a NPE happens. For context, the full exception that gets thrown in this case is
```
main[1] dump e
 e = {
    serialVersionUID: 5162710183389028792
    java.lang.RuntimeException.serialVersionUID: -7034897190745766939
    java.lang.Exception.serialVersionUID: -3387516993124229948
    java.lang.Throwable.serialVersionUID: -3042686055658047285
    java.lang.Throwable.detailMessage: null
    java.lang.Throwable.UNASSIGNED_STACK: instance of java.lang.StackTraceElement[0] (id=1183)
    java.lang.Throwable.cause: instance of java.lang.NullPointerException(id=1182)
    java.lang.Throwable.stackTrace: instance of java.lang.StackTraceElement[0] (id=1183)
    java.lang.Throwable.SUPPRESSED_SENTINEL: instance of java.util.Collections$UnmodifiableRandomAccessList(id=1184)
    java.lang.Throwable.suppressedExceptions: instance of java.util.Collections$UnmodifiableRandomAccessList(id=1184)
    java.lang.Throwable.NULL_CAUSE_MESSAGE: "Cannot suppress a null exception."
    java.lang.Throwable.SELF_SUPPRESSION_MESSAGE: "Self-suppression not permitted"
    java.lang.Throwable.CAUSE_CAPTION: "Caused by: "
    java.lang.Throwable.SUPPRESSED_CAPTION: "Suppressed: "
    java.lang.Throwable.EMPTY_THROWABLE_ARRAY: instance of java.lang.Throwable[0] (id=1189)
    java.lang.Throwable.$assertionsDisabled: true
}
```
Not sure if we can extract the actual source of the NPE as well, but anything more than `null` would help the caller debug a bit more.

**Comment by JordonPhillips** [comment]
Thanks for the report! I opened a little pr to address this. Regarding printing more information, we don't really have anything but the stack trace to work with, and we've already got an argument to print that. We should print something more descriptive though to point people at that / our issue tracker.
