### ISSUE TITLE
Clarification on how to serialize NaN, Infinity, and NegInfinity for AWS protocols

### ISSUE THREAD

**Issue by jdisanti** [awslabs/smithy#812]
I wasn't able to find information in the specifications on how to handle `NaN` or `Infinity` values for floating points for either serialization or deserialization of the protocols. What is the expected behavior for these values?

**Comment by JordonPhillips** [comment]
That's a good question. I think this will have to be protocol specific behavior. I'm still looking into this, but it seems that the JSON protocols don't support those values (as JSON doesn't). restXML appears to accept them and respond to them fine, but it's unclear whether any service does anything with them (the answer is almost certainly that they don't). Currently unsure about awsQuery / ec2Query

**Comment by JordonPhillips** [comment]
I've looked into this, and it looks like existing services theoretically *can* support these special values when handled as a string. I'll work on a PR to add these explicitly to the spec.
