### ISSUE TITLE
protocol tests for primitive 0 zero-value serialization

### ISSUE THREAD

**Issue by rcoh** [awslabs/smithy#817]
0-value serialization when:
- optional primitive numeric
- required primitive numeric
- optional primitive bool
- required primitive bool

Since serializers will usually not share this behavior, it's important to cover this for all relevant protocols:
- awsQuery
- restXml
- restJson
- awsJson

ecQuery is a special case here–in ec2Query all members should be considered boxed.

**Comment by mtdowling** [comment]
These are all covered in IDL v2 that will ship soon.
