### ISSUE TITLE
Update Ec2Query Specification on response serialization

### ISSUE THREAD

**Issue by wooj2** [awslabs/smithy#820]
**Observed behavior:**
* The Ec2Query Specification, located here: https://awslabs.github.io/smithy/1.0/spec/aws/aws-ec2-query-protocol.html#response-serialization, indicates "A nested element, with the name of the operation's output suffixed with "Result", contains the contents of the successful response."
* When calling ec2 using the CLI w/ debug on, I am unable to observe a nested element suffixed with "Result".
For example:
```
aws ec2 describe-regions --debug
```
outputs:
```
2021-06-08 09:16:17,441 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>
    <DescribeRegionsResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
        <requestId>REDACTED</requestId>
            <regionInfo>
                <item>
                    <regionName>eu-north-1</regionName>
.... snip...
```

**Expected Behavior**
1.  We should update:
* The specification to remove the mention of a nested element
* The sample response in the specification
2.  It would be nice to update the specification to describe the RequestId

**Comment by mtdowling** [comment]
Fixed in https://github.com/awslabs/smithy/pull/823
