### ISSUE TITLE
How to combine different smithy files into a single model

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#826]
Hi,

I'd like to be able to define different portions of a service in separate smithy model files. What tooling exists to be able to merge these into a single model and process them accordingly?

**Comment by mtdowling** [comment]
The reference implementation of Smithy is implemented in Java, and we provide a Gradle plugin that can be used to load models, validate them, and build stuff from them using plugins. The Gradle plugin is documented here, including directory layouts: https://awslabs.github.io/smithy/1.0/guides/building-models/gradle-plugin.html. Other examples can be found here (also linked from the above doc): https://github.com/awslabs/smithy-gradle-plugin/tree/main/examples.

With the Gradle plugin, you just put all your model files in the `model` directory, and it will automatically combine them.
