### ISSUE TITLE
How to set openapi servers field

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#834]
Hi,

OpenAPI 3.0 uses the `servers` field to setup basePath and other mappings in AWS API Gateway:
https://swagger.io/docs/specification/api-host-and-base-path/

How does one define these using Smithy?

**Comment by kstich** [comment]
Smithy doesn't currently support providing this information as part of the service or in a trait for the service. If you want to inject the servers configuration into your OpenAPI, then [you can use jsonAdd to do so.](https://awslabs.github.io/smithy/1.0/guides/converting-to-openapi.html#generate-openapi-setting-jsonadd)

For example:

```
{
    "version": "1.0",
    "plugins": {
        "openapi": {
            "service": "smithy.example#Weather",
            "jsonAdd": {
                "/servers": [
                    {
                        "url": "https://example.com"
                    }
                ]
            }
        }
    }
}
```

**Comment by jabalsad** [comment]
Thanks. This should work for the moment.
