### ISSUE TITLE
Include built artifacts (`.jar` and `.tar`/`.zip` archives) with releases

### ISSUE THREAD

**Issue by lunaris** [awslabs/smithy#854]
The `smithy-VERSION.tar`/`smithy-VERSION.zip` archives that are built under e.g. `smithy-cli/build/distributions` (for example) seem like useful things to expose to people who just want to get going/use the command-line interface to render models as JSON. Is there any reason why it would be a bad/useless idea to include these as part of the releases tagged in GitHub?

**Comment by JordonPhillips** [comment]
We've talked about distributing a pre-built version of the CLI as a standalone tool, and have made [some progress in that direction](https://github.com/awslabs/smithy/pull/832). One barrier to this is having a way to resolve dependencies outside of the context of gradle.

**Comment by hpmellema** [comment]
We now include CLI artifacts in the [release](https://github.com/awslabs/smithy/releases/) for the repo.
The CLI can also be installed by following the guide [here](https://smithy.io/2.0/guides/smithy-cli/cli_installation.html)

See CLI release blog post: https://aws.amazon.com/blogs/developer/introducing-the-smithy-cli/
