### ISSUE TITLE
Convert member names to underscore case when generating openAPI spec

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#880]
Hi,

The format guideline says member names must strictly be lower camel case. How can we convert these member names to underscore case when generating the OpenAPI specification?

**Comment by mtdowling** [comment]
OpenAPI specifications define the concrete wire format, and property names defined in them need to match what you'd send on the wire. You influence that by adding the `jsonName` trait to a member: https://awslabs.github.io/smithy/1.0/spec/core/protocol-traits.html#jsonname-trait

**Comment by jabalsad** [comment]
Thanks!

**Comment by jabalsad** [comment]
What if we simply defined the members using underscore casing?

**Comment by mtdowling** [comment]
Yes, you can do that too.
