### ISSUE TITLE
Layout issues in HTML docs

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy#886]
Page: https://awslabs.github.io/smithy/implementations.html?highlight=cli

Issue:

![Screenshot from 2021-08-10 14-09-58](https://user-images.githubusercontent.com/65979407/128935551-23ee8400-1266-4017-a8ce-1562b701c712.png)

Notice the table in "Build Tooling" escapes it's container and the text is cut.

**Comment by cdmatta** [comment]
The problem appears due to a lack of space resulting from the use of code-block (which takes us precious space due to padding) and then a long text withing this block for ex `smithy-cli/build/image/smithy-cli-linux-aarch_64/bin/smithy --help`

After 56 characters the container overflows

**Comment by mtdowling** [comment]
We switched to using the Furo Sphinx theme.
