### ISSUE TITLE
Add `errors` to service shape

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy#894]
It's a common pattern in APIs to support a set of errors across all operations. An `errors` property could be added to the `service` shape to add a list of errors to every operation within the closure of the service.

**Comment by Baccata** [comment]
I've actually implemented that in my protocol, as in, my protocol trait has a field to reference common errors within a service. It implies some pre-processing to forward the errors from the service to the operations, but having it out of the box would be great.
