### ISSUE TITLE
Spreading smithy definitions across files

### ISSUE THREAD

**Issue by jabalsad** [awslabs/smithy#922]
Hi,

It would be really nice if we could define smithy structures and operations across multiple files, and include or reference them somehow. It doesn't seem like the specification currently allows for this. Our model is large, and having files just makes organizing and finding things a little easier.

Thanks!

**Comment by gosar** [comment]
I @jabalsad . This is already supported. 

> The model files that make up a semantic model MAY be split across multiple files to improve readability or modularity

See https://awslabs.github.io/smithy/1.0/spec/core/model.html#model-files for more details.

See https://awslabs.github.io/smithy/1.0/guides/building-models/gradle-plugin.html#smithy-model-sources for details about how the Gradle plugin handles different source files. And see this example https://github.com/awslabs/smithy-gradle-plugin/tree/main/examples/multiple-sources

Please let us know if you meant something else.
