### ISSUE TITLE
Best practices for use cases requiring nullary union members

### ISSUE THREAD

**Issue by lunaris** [awslabs/smithy#928]
Smithy's `@enum` trait supports use cases in which a value must be one of a known set:

```smithy
@enum([
  {
    name: "FIRST",
    value: "FIRST",
  },
  {
    name: "SECOND",
    value: "SECOND",
  },
])
string MyEnum
```

which when generating TypeScript code (say) could produce:

```typescript
type MyEnum = "FIRST" | "SECOND"
```

Smithy's `union` shapes support use cases in which a value must have a tag from a known set and some associated value (depending on the tag):

```smithy
union MyUnion {
  first: String,
  second: Long
}
```

which again, when generating TypeScript could produce:

```typescript
type MyUnion =
  | { type: "first"
    , value: string
    }
  | { type: "second"
    , value: bigint
    }
```

TypeScript (and other languages) can also model a hybrid of these two types, where some members/constructors have associated data (as in unions), some don't (as in enumerations), and some have optional values:

```typescript
// In TypeScript
type AnotherUnion =
  | { type: "first"
    , value: string
    }
  | { type: "second"
    , value: bigint
    }
  | { type: "third"
    }
  | { type: "fourth"
    , value: number | null
    }
```

```haskell
-- In Haskell
data AnotherUnion
  = First String
  | Second Integer
  | Third
  | Fourth (Maybe Double)
```

Here `third` is a nullary constructor -- it doesn't have an associated value, but it is distinct from `first`, `second` and `fourth`. `fourth` has a value which can be null/not present. How might we model this in Smithy? We can't do something like:

```smithy
union AnotherUnion {
  @required
  first: String,

  @required
  second: Integer,

  third: Empty,
  fourth: Double
}
```

(where `Empty` is some dummy/to-be-ignored type e.g. `structure Empty {}`) since `@required` is banned inside unions (since unions cannot have null/not present values). Another option might be to use a trait, such as:

```smithy
@sum([
  { name: "first", value: String },
  { name: "second", value: Integer },
  { name: "third" },
  { name: "fourth", value: Double, nullable: true },
])
union AnotherUnion {}
```

but this seems a shame since the fact that `AnotherUnion` is essentially a union is somewhat obscured (also empty unions are forbidden). Does anyone have any thoughts or recommendations on how to approach this? Perhaps this is simply not the way to model this problem? All feedback and critique welcome!

**Comment by lunaris** [comment]
Thanks for the reply and sorry for the delay in responding!

Yes, the "extra constructor" or nested union approaches are what we came up with/what I expect we will use; the challenge is mostly in legacy code we are looking to retrofit Smithy APIs on to. For those interested/coming here later, we are considering a trait-based approach to those APIs. Specifically, we are looking at defining a "unit" trait and an "optional" trait that a code generator can use to generate the `Maybe`-based code. E.g.:

```smithy
@trait 
structure unit {}

@trait 
structure optional {}

@unit 
structure Unit {}

union AnotherUnion {
  first: String,
  second: Integer,
  third: Unit,

  @optional
  fourth: Double,
}
```

Thanks again for the detailed response and consideration! Happy to close this issue.

**Comment by mtdowling** [comment]
I could see a `@unit` trait being added to Smithy. I think the only place it makes sense is tagged union members, right?
