### ISSUE TITLE
Specification for deserialising @httpQueryParams

### ISSUE THREAD

**Issue by lunaris** [awslabs/smithy#956]
The specification states that `@httpQueryParams` can only be used on operation inputs, and gives rules about how such inputs should be serialised when making and sending requests. It doesn't (I believe), however, talk about how to deserialise/parse query parameters (e.g. in [generated] server-side code) when receiving requests. Specifically, it's not clear how to handle query string parameters that do not have values.

For instance, given these Smithy definitions:

```smithy
operation MyOperation {
  input: MyInput
}

structure MyInput {
  @httpQueryParams
  myQueryParams: MyMap
}

map MyMap {
  key: String,
  value: String
}
```

Serialising a request is specified and makes sense -- supposing we have a map with entries `("first", "1")` and `("second", "true")` we must produce `?first=1&second=true`. However, suppose we receive a request with the query string `?first=1&second&third=false`. What should we do? Options I can think of:

1. Discard all keys for which there is no value (here `second`), yielding `("first", "1"), ("third", "false")`
2. Treat the `MyMap` map shape as though it were `@sparse`, permitting us to have optional values in it, and store all keys, yielding `("first", "1"), ("second", null), ("third", "false")`
3. Discard all keys, yielding an empty map
4. Throw an error (e.g. `400 Bad Request`) and require that all keys must have values

Thoughts welcome and apologies if I have missed something that clears this up in the spec.

**Comment by adamthom-amzn** [comment]
Closing this as I think the associated pull request (thanks for the contribution!) covered what you were looking for.
