### ISSUE TITLE
How can I generate a model that does not include the aws Trait definition?

### ISSUE THREAD

**Issue by fuku2014** [awslabs/smithy#974]
I want to use smithy to make a model like [sdk json](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models).  
It looks like these JSONs don't contain aws Trait definitions, For example like `aws.protocols#awsJson1_1` .  

But It will be included in the model I generated.  
How can I generate a model that does not include the Trait definition like [sdk json](https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models)?  

`model/main.smithy`
``` smithy
namespace com.example

use aws.api#service

@service(sdkId: "example")
service Example {
    version: "2021-12-08",
    operations: [
        CreateExample,
    ],
}

operation CreateExample {
    input: CreateExampleRequest,
    output: CreateExampleResult,
}

structure CreateExampleRequest {
    Description: String,
}

structure CreateExampleResult {
    Description: String,
}
```

`smithy-build.json`
```json
{
    "version": "1.0",
    "projections": {
        "example": {
            "transforms": [
                {
                   "name": "includeServices",
                    "args": {
                        "services": ["com.example#Example"]
                    }
               },
              {
                  "name": "removeUnusedShapes"
              }
            ]
        }
}
```

`build.gradle.kts`
```kotlin
plugins {
    id("software.amazon.smithy").version("0.5.3")
}

dependencies {
    implementation("software.amazon.smithy:smithy-model:1.13.1")
    implementation("software.amazon.smithy:smithy-aws-traits:1.13.1")
}

tasks["jar"].enabled = false

repositories {
    mavenLocal()
    mavenCentral()
}
```

**Comment by kstich** [comment]
You can use [the `removeTraitDefinitions` transform](https://awslabs.github.io/smithy/1.0/guides/building-models/build-config.html#removetraitdefinitions) in your projection to remove the trait _definitions_ but leave the instances of traits intact on any shapes.

**Comment by fuku2014** [comment]
@kstich 

Thank you for your help!!  

I tried defining `removeTraitDefinitions`.

`smithy-build.json`
```json
{
    "version": "1.0",
    "projections": {
        "example": {
            "transforms": [
                {
                   "name": "includeServices",
                    "args": {
                        "services": ["com.example#Example"]
                    }
                },
                {
                    "name": "removeUnusedShapes"
                },
                {
                    "name": "removeTraitDefinitions"
                }
            ]
        }
}
```

But Smithy returns a validation error.

```console
[ERROR] com.example#Example: Unable to resolve trait `aws.api#service`. If this is a custom trait, then it must be defined before it can be used in a model. 
```

How can this error be resolved?

**Comment by kstich** [comment]
Since you're building a projection, you'll need to declare the proper dependencies in `buildscript`. [You can read more about configuring the dependencies for a projection build with the Gradle plugin here.](https://awslabs.github.io/smithy/1.0/guides/building-models/gradle-plugin.html#generating-a-projection)

**Comment by fuku2014** [comment]
Thank you! 👍 

I will read this document!
