### ISSUE TITLE
`uri` in the `@http` trait accepts UTF-8

### ISSUE THREAD

**Issue by david-perez** [awslabs/smithy#975]
https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#uri

As of writing, Smithy accepts e.g. `@http(method: "PUT", uri: "/service/小路/💙/طريق")`. It probably should just accept ASCII, as per [this URL spec](https://url.spec.whatwg.org/#url-representation) .

Everything seems to be just ASCII, so [the endpoint trait](https://url.spec.whatwg.org/#url-representation), which defines host prefixes, is probably affected as well.

**Comment by mtdowling** [comment]
RFC 7230 refers to RFC 3986 for the allowed characters of a request's `request-target`, and you're right that it doesn't accept arbitrary UTF-8: https://datatracker.ietf.org/doc/html/rfc3986#section-3.3. We should update the spec to make this clear and add validation.

**Comment by david-perez** [comment]
What about the endpoint trait?
