### ISSUE TITLE
Add enum support to byte, short, int, and long

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy#98]
The `enum` trait today can only be attached to a string shape. Updating this trait to also support byte, short, int, and long would make it support a broader range of uses cases that involve a finite set of numeric values.

**Comment by mtdowling** [comment]
Closing this until we get actual customer requests for it.

**Comment by anjalig6** [comment]
It would be great if we could get support for all the primitive types in enum i.e. byte, short, int, long, float, double, boolean, bigInteger, bigDecimal etc

**Comment by bhardwaj-shubham12** [comment]
> It would be great if we could get support for all the primitive types in enum i.e. byte, short, int, long, float, double, boolean, bigInteger, bigDecimal etc

The feature would be of great benefit.

**Comment by akdev1l** [comment]
I am an Amazon employee (though this GH account isn't tied to Amazon) and I am using smithy to build a service as part of my duties at Amazon

It'd be great if we had this feature as currently there's no way of encoding constants that may be part of an API.

Would you consider this an actual customer request? Let me know if there are more appropriate channels for this exchange.

**Comment by mtdowling** [comment]
We have intEnum and string enums now in Smithy IDL 2.0. Each new shape requires a new type, we have to do tricky things like subclass an existing type (e.g., intEnum extends from integer, and string enum extends from string), and each type is more overhead for people trying to figure out how Smithy works. I think intEnum and string enums cover the vast majority of use cases, so I don't think there would be alot of value in expanding enums to support all these types.

**Comment by akdev1l** [comment]
thank you! that solves my issue - must have missed it in the documentation

I'll leave it here in case someone else finds this issue looking for the same information: https://awslabs.github.io/smithy/2.0/spec/simple-types.html#intenum
