### ISSUE TITLE
Update Smithy OpenAPI model transform to 3.1.0

### ISSUE THREAD

**Issue by mtdowling** [awslabs/smithy#985]
The Smithy -> OpenAPI converter currently supports 3.0.2, but OpenAPI is now at 3.1.0. We need to update the converter to 3.1.0, and ensure that Amazon API Gateway can support this version too.

**Comment by eduardomourar** [comment]
Just tried deploying an API Gateway resource today (June 2nd, 2022) with OpenAPI v3.1.0, and I get the following error:
> Invalid OpenAPI input.
This does seem to align with its documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html
